// Code generated by protoc-gen-go. DO NOT EDIT.
// source: warehouse.proto

package warehouse

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WarehouseMessages struct {
	// Types that are valid to be assigned to WarehouseMessage:
	//	*WarehouseMessages_StockCorrected
	WarehouseMessage     isWarehouseMessages_WarehouseMessage `protobuf_oneof:"warehouseMessage"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *WarehouseMessages) Reset()         { *m = WarehouseMessages{} }
func (m *WarehouseMessages) String() string { return proto.CompactTextString(m) }
func (*WarehouseMessages) ProtoMessage()    {}
func (*WarehouseMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_warehouse_8a9d02284c44bb28, []int{0}
}
func (m *WarehouseMessages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WarehouseMessages.Unmarshal(m, b)
}
func (m *WarehouseMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WarehouseMessages.Marshal(b, m, deterministic)
}
func (dst *WarehouseMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WarehouseMessages.Merge(dst, src)
}
func (m *WarehouseMessages) XXX_Size() int {
	return xxx_messageInfo_WarehouseMessages.Size(m)
}
func (m *WarehouseMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_WarehouseMessages.DiscardUnknown(m)
}

var xxx_messageInfo_WarehouseMessages proto.InternalMessageInfo

type isWarehouseMessages_WarehouseMessage interface {
	isWarehouseMessages_WarehouseMessage()
}

type WarehouseMessages_StockCorrected struct {
	StockCorrected *StockCorrected `protobuf:"bytes,1,opt,name=stockCorrected,proto3,oneof"`
}

func (*WarehouseMessages_StockCorrected) isWarehouseMessages_WarehouseMessage() {}

func (m *WarehouseMessages) GetWarehouseMessage() isWarehouseMessages_WarehouseMessage {
	if m != nil {
		return m.WarehouseMessage
	}
	return nil
}

func (m *WarehouseMessages) GetStockCorrected() *StockCorrected {
	if x, ok := m.GetWarehouseMessage().(*WarehouseMessages_StockCorrected); ok {
		return x.StockCorrected
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*WarehouseMessages) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _WarehouseMessages_OneofMarshaler, _WarehouseMessages_OneofUnmarshaler, _WarehouseMessages_OneofSizer, []interface{}{
		(*WarehouseMessages_StockCorrected)(nil),
	}
}

func _WarehouseMessages_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*WarehouseMessages)
	// warehouseMessage
	switch x := m.WarehouseMessage.(type) {
	case *WarehouseMessages_StockCorrected:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.StockCorrected); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("WarehouseMessages.WarehouseMessage has unexpected type %T", x)
	}
	return nil
}

func _WarehouseMessages_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*WarehouseMessages)
	switch tag {
	case 1: // warehouseMessage.stockCorrected
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StockCorrected)
		err := b.DecodeMessage(msg)
		m.WarehouseMessage = &WarehouseMessages_StockCorrected{msg}
		return true, err
	default:
		return false, nil
	}
}

func _WarehouseMessages_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*WarehouseMessages)
	// warehouseMessage
	switch x := m.WarehouseMessage.(type) {
	case *WarehouseMessages_StockCorrected:
		s := proto.Size(x.StockCorrected)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type StockCorrected struct {
	ProductID            string   `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	Quantity             int64    `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockCorrected) Reset()         { *m = StockCorrected{} }
func (m *StockCorrected) String() string { return proto.CompactTextString(m) }
func (*StockCorrected) ProtoMessage()    {}
func (*StockCorrected) Descriptor() ([]byte, []int) {
	return fileDescriptor_warehouse_8a9d02284c44bb28, []int{1}
}
func (m *StockCorrected) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockCorrected.Unmarshal(m, b)
}
func (m *StockCorrected) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockCorrected.Marshal(b, m, deterministic)
}
func (dst *StockCorrected) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockCorrected.Merge(dst, src)
}
func (m *StockCorrected) XXX_Size() int {
	return xxx_messageInfo_StockCorrected.Size(m)
}
func (m *StockCorrected) XXX_DiscardUnknown() {
	xxx_messageInfo_StockCorrected.DiscardUnknown(m)
}

var xxx_messageInfo_StockCorrected proto.InternalMessageInfo

func (m *StockCorrected) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *StockCorrected) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func init() {
	proto.RegisterType((*WarehouseMessages)(nil), "warehouse.WarehouseMessages")
	proto.RegisterType((*StockCorrected)(nil), "warehouse.StockCorrected")
}

func init() { proto.RegisterFile("warehouse.proto", fileDescriptor_warehouse_8a9d02284c44bb28) }

var fileDescriptor_warehouse_8a9d02284c44bb28 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x4f, 0x2c, 0x4a,
	0xcd, 0xc8, 0x2f, 0x2d, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0xe5, 0x70, 0x09, 0x86, 0xc3, 0x38, 0xbe, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0xc5, 0x42, 0xce,
	0x5c, 0x7c, 0xc5, 0x25, 0xf9, 0xc9, 0xd9, 0xce, 0xf9, 0x45, 0x45, 0xa9, 0xc9, 0x25, 0xa9, 0x29,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x92, 0x7a, 0x08, 0x93, 0x82, 0x51, 0x14, 0x78, 0x30,
	0x04, 0xa1, 0x69, 0x71, 0x12, 0xe2, 0x12, 0x28, 0x47, 0x33, 0x59, 0xc9, 0x8b, 0x8b, 0x0f, 0x55,
	0x9f, 0x90, 0x0c, 0x17, 0x67, 0x41, 0x51, 0x7e, 0x4a, 0x69, 0x72, 0x89, 0xa7, 0x0b, 0xd8, 0x16,
	0xce, 0x20, 0x84, 0x80, 0x90, 0x14, 0x17, 0x47, 0x61, 0x69, 0x62, 0x5e, 0x49, 0x66, 0x49, 0xa5,
	0x04, 0x93, 0x02, 0xa3, 0x06, 0x73, 0x10, 0x9c, 0x9f, 0xc4, 0x06, 0xf6, 0x8b, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0xb3, 0x38, 0x02, 0x6e, 0xde, 0x00, 0x00, 0x00,
}
