version: '3.7'

services:

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment: 
      - BROKER_LIST=kafka:9092
    ports:
      - '8080:8080'
    networks:
      - shared_event-store
    read_only: true
    volumes:
      - ./:/go/src/app/:rw,cached
    user: '${UID}:${GID}'
    cap_drop: [ALL]
    restart: unless-stopped

networks:
  shared_event-store:
    external: true
