// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/pb/products.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CartChangeAction int32

const (
	CartChangeAction_add    CartChangeAction = 0
	CartChangeAction_remove CartChangeAction = 1
)

var CartChangeAction_name = map[int32]string{
	0: "add",
	1: "remove",
}
var CartChangeAction_value = map[string]int32{
	"add":    0,
	"remove": 1,
}

func (x CartChangeAction) String() string {
	return proto.EnumName(CartChangeAction_name, int32(x))
}
func (CartChangeAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_products_53d02201a5603c61, []int{0}
}

type Product struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Longtext             string   `protobuf:"bytes,4,opt,name=longtext,proto3" json:"longtext,omitempty"`
	Category             string   `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`
	SmallImageURL        string   `protobuf:"bytes,5,opt,name=smallImageURL,proto3" json:"smallImageURL,omitempty"`
	LargeImageURL        string   `protobuf:"bytes,6,opt,name=largeImageURL,proto3" json:"largeImageURL,omitempty"`
	Price                float32  `protobuf:"fixed32,7,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_53d02201a5603c61, []int{0}
}
func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (dst *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(dst, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Product) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetLongtext() string {
	if m != nil {
		return m.Longtext
	}
	return ""
}

func (m *Product) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Product) GetSmallImageURL() string {
	if m != nil {
		return m.SmallImageURL
	}
	return ""
}

func (m *Product) GetLargeImageURL() string {
	if m != nil {
		return m.LargeImageURL
	}
	return ""
}

func (m *Product) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type ProductUpdate struct {
	Old                  *Product `protobuf:"bytes,1,opt,name=old,proto3" json:"old,omitempty"`
	New                  *Product `protobuf:"bytes,2,opt,name=new,proto3" json:"new,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductUpdate) Reset()         { *m = ProductUpdate{} }
func (m *ProductUpdate) String() string { return proto.CompactTextString(m) }
func (*ProductUpdate) ProtoMessage()    {}
func (*ProductUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_53d02201a5603c61, []int{1}
}
func (m *ProductUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductUpdate.Unmarshal(m, b)
}
func (m *ProductUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductUpdate.Marshal(b, m, deterministic)
}
func (dst *ProductUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductUpdate.Merge(dst, src)
}
func (m *ProductUpdate) XXX_Size() int {
	return xxx_messageInfo_ProductUpdate.Size(m)
}
func (m *ProductUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ProductUpdate proto.InternalMessageInfo

func (m *ProductUpdate) GetOld() *Product {
	if m != nil {
		return m.Old
	}
	return nil
}

func (m *ProductUpdate) GetNew() *Product {
	if m != nil {
		return m.New
	}
	return nil
}

type CartChange struct {
	Uuid                 string           `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Action               CartChangeAction `protobuf:"varint,2,opt,name=action,proto3,enum=pb.CartChangeAction" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CartChange) Reset()         { *m = CartChange{} }
func (m *CartChange) String() string { return proto.CompactTextString(m) }
func (*CartChange) ProtoMessage()    {}
func (*CartChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_53d02201a5603c61, []int{2}
}
func (m *CartChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CartChange.Unmarshal(m, b)
}
func (m *CartChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CartChange.Marshal(b, m, deterministic)
}
func (dst *CartChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CartChange.Merge(dst, src)
}
func (m *CartChange) XXX_Size() int {
	return xxx_messageInfo_CartChange.Size(m)
}
func (m *CartChange) XXX_DiscardUnknown() {
	xxx_messageInfo_CartChange.DiscardUnknown(m)
}

var xxx_messageInfo_CartChange proto.InternalMessageInfo

func (m *CartChange) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *CartChange) GetAction() CartChangeAction {
	if m != nil {
		return m.Action
	}
	return CartChangeAction_add
}

type Stock struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Quantity             int64    `protobuf:"zigzag64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stock) Reset()         { *m = Stock{} }
func (m *Stock) String() string { return proto.CompactTextString(m) }
func (*Stock) ProtoMessage()    {}
func (*Stock) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_53d02201a5603c61, []int{3}
}
func (m *Stock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stock.Unmarshal(m, b)
}
func (m *Stock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stock.Marshal(b, m, deterministic)
}
func (dst *Stock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stock.Merge(dst, src)
}
func (m *Stock) XXX_Size() int {
	return xxx_messageInfo_Stock.Size(m)
}
func (m *Stock) XXX_DiscardUnknown() {
	xxx_messageInfo_Stock.DiscardUnknown(m)
}

var xxx_messageInfo_Stock proto.InternalMessageInfo

func (m *Stock) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Stock) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func init() {
	proto.RegisterType((*Product)(nil), "pb.Product")
	proto.RegisterType((*ProductUpdate)(nil), "pb.ProductUpdate")
	proto.RegisterType((*CartChange)(nil), "pb.CartChange")
	proto.RegisterType((*Stock)(nil), "pb.Stock")
	proto.RegisterEnum("pb.CartChangeAction", CartChangeAction_name, CartChangeAction_value)
}

func init() { proto.RegisterFile("pkg/pb/products.proto", fileDescriptor_products_53d02201a5603c61) }

var fileDescriptor_products_53d02201a5603c61 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x5f, 0x4b, 0xf3, 0x30,
	0x14, 0xc6, 0xdf, 0xee, 0x4f, 0xb7, 0xf7, 0x8c, 0xc9, 0x08, 0x13, 0xc2, 0x40, 0x18, 0x45, 0x70,
	0x88, 0x6c, 0x30, 0x2f, 0xbc, 0x96, 0x5d, 0x09, 0x2a, 0x52, 0xd9, 0x07, 0x48, 0xdb, 0x43, 0x2d,
	0xeb, 0x92, 0x98, 0x9d, 0x3a, 0xf7, 0xa9, 0xfd, 0x0a, 0x92, 0x64, 0x56, 0x37, 0x76, 0x97, 0xe7,
	0xf9, 0x3d, 0x79, 0xc8, 0x39, 0x81, 0x73, 0xbd, 0xca, 0x67, 0x3a, 0x99, 0x69, 0xa3, 0xb2, 0x2a,
	0xa5, 0xcd, 0x54, 0x1b, 0x45, 0x8a, 0x35, 0x74, 0x12, 0x7d, 0x05, 0xd0, 0x79, 0xf1, 0x36, 0x63,
	0xd0, 0xaa, 0xaa, 0x22, 0xe3, 0xc1, 0x38, 0x98, 0xfc, 0x8f, 0xdd, 0x99, 0x0d, 0xa1, 0x4d, 0x05,
	0x95, 0xc8, 0x1b, 0xce, 0xf4, 0x82, 0x8d, 0xa1, 0x97, 0xe1, 0x26, 0x35, 0x85, 0xa6, 0x42, 0x49,
	0xde, 0x74, 0xec, 0xaf, 0xc5, 0x46, 0xd0, 0x2d, 0x95, 0xcc, 0x09, 0x3f, 0x89, 0xb7, 0x1c, 0xae,
	0xb5, 0x65, 0xa9, 0x20, 0xcc, 0x95, 0xd9, 0xf1, 0xae, 0x67, 0x3f, 0x9a, 0x5d, 0x42, 0x7f, 0xb3,
	0x16, 0x65, 0xf9, 0xb0, 0x16, 0x39, 0x2e, 0xe3, 0x47, 0xde, 0x76, 0x81, 0x43, 0xd3, 0xa6, 0x4a,
	0x61, 0x72, 0xac, 0x53, 0xa1, 0x4f, 0x1d, 0x98, 0xf6, 0xed, 0xda, 0x14, 0x29, 0xf2, 0xce, 0x38,
	0x98, 0x34, 0x62, 0x2f, 0xa2, 0x27, 0xe8, 0xef, 0x07, 0x5e, 0xea, 0x4c, 0x10, 0xb2, 0x0b, 0x68,
	0xaa, 0xd2, 0x4f, 0xdd, 0x9b, 0xf7, 0xa6, 0x3a, 0x99, 0xee, 0x79, 0x6c, 0x7d, 0x8b, 0x25, 0x6e,
	0xdd, 0xfc, 0xc7, 0x58, 0xe2, 0x36, 0x7a, 0x06, 0x58, 0x08, 0x43, 0x8b, 0x37, 0x21, 0x73, 0x3c,
	0xb9, 0xc2, 0x1b, 0x08, 0x45, 0xea, 0xf6, 0x64, 0x3b, 0xce, 0xe6, 0x43, 0xdb, 0xf1, 0x7b, 0xe7,
	0xde, 0xb1, 0x78, 0x9f, 0x89, 0xee, 0xa0, 0xfd, 0x4a, 0x2a, 0x5d, 0x9d, 0xac, 0x1a, 0x41, 0xf7,
	0xbd, 0x12, 0x92, 0x0a, 0xda, 0xb9, 0x32, 0x16, 0xd7, 0xfa, 0xfa, 0x0a, 0x06, 0xc7, 0xa5, 0xac,
	0x03, 0x4d, 0x91, 0x65, 0x83, 0x7f, 0x0c, 0x20, 0x34, 0xb8, 0x56, 0x1f, 0x38, 0x08, 0x92, 0xd0,
	0xfd, 0xfe, 0xed, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x21, 0x50, 0xc2, 0xfd, 0x16, 0x02, 0x00,
	0x00,
}
