// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/pb/products.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CartChangeAction int32

const (
	CartChangeAction_add    CartChangeAction = 0
	CartChangeAction_remove CartChangeAction = 1
)

var CartChangeAction_name = map[int32]string{
	0: "add",
	1: "remove",
}
var CartChangeAction_value = map[string]int32{
	"add":    0,
	"remove": 1,
}

func (x CartChangeAction) String() string {
	return proto.EnumName(CartChangeAction_name, int32(x))
}
func (CartChangeAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_products_0baae3255f3d560b, []int{0}
}

type Product struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Longtext             string   `protobuf:"bytes,4,opt,name=longtext,proto3" json:"longtext,omitempty"`
	Category             string   `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`
	SmallImageURL        string   `protobuf:"bytes,5,opt,name=smallImageURL,proto3" json:"smallImageURL,omitempty"`
	LargeImageURL        string   `protobuf:"bytes,6,opt,name=largeImageURL,proto3" json:"largeImageURL,omitempty"`
	Price                float32  `protobuf:"fixed32,7,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_0baae3255f3d560b, []int{0}
}
func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (dst *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(dst, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Product) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetLongtext() string {
	if m != nil {
		return m.Longtext
	}
	return ""
}

func (m *Product) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Product) GetSmallImageURL() string {
	if m != nil {
		return m.SmallImageURL
	}
	return ""
}

func (m *Product) GetLargeImageURL() string {
	if m != nil {
		return m.LargeImageURL
	}
	return ""
}

func (m *Product) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type ProductUpdate struct {
	Old                  *Product `protobuf:"bytes,1,opt,name=old,proto3" json:"old,omitempty"`
	New                  *Product `protobuf:"bytes,2,opt,name=new,proto3" json:"new,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductUpdate) Reset()         { *m = ProductUpdate{} }
func (m *ProductUpdate) String() string { return proto.CompactTextString(m) }
func (*ProductUpdate) ProtoMessage()    {}
func (*ProductUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_0baae3255f3d560b, []int{1}
}
func (m *ProductUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductUpdate.Unmarshal(m, b)
}
func (m *ProductUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductUpdate.Marshal(b, m, deterministic)
}
func (dst *ProductUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductUpdate.Merge(dst, src)
}
func (m *ProductUpdate) XXX_Size() int {
	return xxx_messageInfo_ProductUpdate.Size(m)
}
func (m *ProductUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ProductUpdate proto.InternalMessageInfo

func (m *ProductUpdate) GetOld() *Product {
	if m != nil {
		return m.Old
	}
	return nil
}

func (m *ProductUpdate) GetNew() *Product {
	if m != nil {
		return m.New
	}
	return nil
}

type CheckoutContext struct {
	// Types that are valid to be assigned to CheckoutContext:
	//	*CheckoutContext_CartChange
	//	*CheckoutContext_Stock
	//	*CheckoutContext_ProductUpdate
	//	*CheckoutContext_CartOrder
	CheckoutContext      isCheckoutContext_CheckoutContext `protobuf_oneof:"checkoutContext"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *CheckoutContext) Reset()         { *m = CheckoutContext{} }
func (m *CheckoutContext) String() string { return proto.CompactTextString(m) }
func (*CheckoutContext) ProtoMessage()    {}
func (*CheckoutContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_0baae3255f3d560b, []int{2}
}
func (m *CheckoutContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckoutContext.Unmarshal(m, b)
}
func (m *CheckoutContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckoutContext.Marshal(b, m, deterministic)
}
func (dst *CheckoutContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckoutContext.Merge(dst, src)
}
func (m *CheckoutContext) XXX_Size() int {
	return xxx_messageInfo_CheckoutContext.Size(m)
}
func (m *CheckoutContext) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckoutContext.DiscardUnknown(m)
}

var xxx_messageInfo_CheckoutContext proto.InternalMessageInfo

type isCheckoutContext_CheckoutContext interface {
	isCheckoutContext_CheckoutContext()
}

type CheckoutContext_CartChange struct {
	CartChange *CartChange `protobuf:"bytes,1,opt,name=cartChange,proto3,oneof"`
}

type CheckoutContext_Stock struct {
	Stock *Stock `protobuf:"bytes,2,opt,name=stock,proto3,oneof"`
}

type CheckoutContext_ProductUpdate struct {
	ProductUpdate *ProductUpdate `protobuf:"bytes,3,opt,name=productUpdate,proto3,oneof"`
}

type CheckoutContext_CartOrder struct {
	CartOrder *CartOrder `protobuf:"bytes,4,opt,name=cartOrder,proto3,oneof"`
}

func (*CheckoutContext_CartChange) isCheckoutContext_CheckoutContext() {}

func (*CheckoutContext_Stock) isCheckoutContext_CheckoutContext() {}

func (*CheckoutContext_ProductUpdate) isCheckoutContext_CheckoutContext() {}

func (*CheckoutContext_CartOrder) isCheckoutContext_CheckoutContext() {}

func (m *CheckoutContext) GetCheckoutContext() isCheckoutContext_CheckoutContext {
	if m != nil {
		return m.CheckoutContext
	}
	return nil
}

func (m *CheckoutContext) GetCartChange() *CartChange {
	if x, ok := m.GetCheckoutContext().(*CheckoutContext_CartChange); ok {
		return x.CartChange
	}
	return nil
}

func (m *CheckoutContext) GetStock() *Stock {
	if x, ok := m.GetCheckoutContext().(*CheckoutContext_Stock); ok {
		return x.Stock
	}
	return nil
}

func (m *CheckoutContext) GetProductUpdate() *ProductUpdate {
	if x, ok := m.GetCheckoutContext().(*CheckoutContext_ProductUpdate); ok {
		return x.ProductUpdate
	}
	return nil
}

func (m *CheckoutContext) GetCartOrder() *CartOrder {
	if x, ok := m.GetCheckoutContext().(*CheckoutContext_CartOrder); ok {
		return x.CartOrder
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CheckoutContext) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _CheckoutContext_OneofMarshaler, _CheckoutContext_OneofUnmarshaler, _CheckoutContext_OneofSizer, []interface{}{
		(*CheckoutContext_CartChange)(nil),
		(*CheckoutContext_Stock)(nil),
		(*CheckoutContext_ProductUpdate)(nil),
		(*CheckoutContext_CartOrder)(nil),
	}
}

func _CheckoutContext_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*CheckoutContext)
	// checkoutContext
	switch x := m.CheckoutContext.(type) {
	case *CheckoutContext_CartChange:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CartChange); err != nil {
			return err
		}
	case *CheckoutContext_Stock:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Stock); err != nil {
			return err
		}
	case *CheckoutContext_ProductUpdate:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ProductUpdate); err != nil {
			return err
		}
	case *CheckoutContext_CartOrder:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CartOrder); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("CheckoutContext.CheckoutContext has unexpected type %T", x)
	}
	return nil
}

func _CheckoutContext_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*CheckoutContext)
	switch tag {
	case 1: // checkoutContext.cartChange
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CartChange)
		err := b.DecodeMessage(msg)
		m.CheckoutContext = &CheckoutContext_CartChange{msg}
		return true, err
	case 2: // checkoutContext.stock
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Stock)
		err := b.DecodeMessage(msg)
		m.CheckoutContext = &CheckoutContext_Stock{msg}
		return true, err
	case 3: // checkoutContext.productUpdate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ProductUpdate)
		err := b.DecodeMessage(msg)
		m.CheckoutContext = &CheckoutContext_ProductUpdate{msg}
		return true, err
	case 4: // checkoutContext.cartOrder
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CartOrder)
		err := b.DecodeMessage(msg)
		m.CheckoutContext = &CheckoutContext_CartOrder{msg}
		return true, err
	default:
		return false, nil
	}
}

func _CheckoutContext_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*CheckoutContext)
	// checkoutContext
	switch x := m.CheckoutContext.(type) {
	case *CheckoutContext_CartChange:
		s := proto.Size(x.CartChange)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CheckoutContext_Stock:
		s := proto.Size(x.Stock)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CheckoutContext_ProductUpdate:
		s := proto.Size(x.ProductUpdate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CheckoutContext_CartOrder:
		s := proto.Size(x.CartOrder)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type CartChange struct {
	CartID               string           `protobuf:"bytes,3,opt,name=cartID,proto3" json:"cartID,omitempty"`
	Uuid                 string           `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Action               CartChangeAction `protobuf:"varint,2,opt,name=action,proto3,enum=pb.CartChangeAction" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CartChange) Reset()         { *m = CartChange{} }
func (m *CartChange) String() string { return proto.CompactTextString(m) }
func (*CartChange) ProtoMessage()    {}
func (*CartChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_0baae3255f3d560b, []int{3}
}
func (m *CartChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CartChange.Unmarshal(m, b)
}
func (m *CartChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CartChange.Marshal(b, m, deterministic)
}
func (dst *CartChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CartChange.Merge(dst, src)
}
func (m *CartChange) XXX_Size() int {
	return xxx_messageInfo_CartChange.Size(m)
}
func (m *CartChange) XXX_DiscardUnknown() {
	xxx_messageInfo_CartChange.DiscardUnknown(m)
}

var xxx_messageInfo_CartChange proto.InternalMessageInfo

func (m *CartChange) GetCartID() string {
	if m != nil {
		return m.CartID
	}
	return ""
}

func (m *CartChange) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *CartChange) GetAction() CartChangeAction {
	if m != nil {
		return m.Action
	}
	return CartChangeAction_add
}

type CartOrder struct {
	CartID               string   `protobuf:"bytes,1,opt,name=cartID,proto3" json:"cartID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CartOrder) Reset()         { *m = CartOrder{} }
func (m *CartOrder) String() string { return proto.CompactTextString(m) }
func (*CartOrder) ProtoMessage()    {}
func (*CartOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_0baae3255f3d560b, []int{4}
}
func (m *CartOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CartOrder.Unmarshal(m, b)
}
func (m *CartOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CartOrder.Marshal(b, m, deterministic)
}
func (dst *CartOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CartOrder.Merge(dst, src)
}
func (m *CartOrder) XXX_Size() int {
	return xxx_messageInfo_CartOrder.Size(m)
}
func (m *CartOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_CartOrder.DiscardUnknown(m)
}

var xxx_messageInfo_CartOrder proto.InternalMessageInfo

func (m *CartOrder) GetCartID() string {
	if m != nil {
		return m.CartID
	}
	return ""
}

type Stock struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Quantity             int64    `protobuf:"zigzag64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stock) Reset()         { *m = Stock{} }
func (m *Stock) String() string { return proto.CompactTextString(m) }
func (*Stock) ProtoMessage()    {}
func (*Stock) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_0baae3255f3d560b, []int{5}
}
func (m *Stock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stock.Unmarshal(m, b)
}
func (m *Stock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stock.Marshal(b, m, deterministic)
}
func (dst *Stock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stock.Merge(dst, src)
}
func (m *Stock) XXX_Size() int {
	return xxx_messageInfo_Stock.Size(m)
}
func (m *Stock) XXX_DiscardUnknown() {
	xxx_messageInfo_Stock.DiscardUnknown(m)
}

var xxx_messageInfo_Stock proto.InternalMessageInfo

func (m *Stock) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Stock) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func init() {
	proto.RegisterType((*Product)(nil), "pb.Product")
	proto.RegisterType((*ProductUpdate)(nil), "pb.ProductUpdate")
	proto.RegisterType((*CheckoutContext)(nil), "pb.CheckoutContext")
	proto.RegisterType((*CartChange)(nil), "pb.CartChange")
	proto.RegisterType((*CartOrder)(nil), "pb.CartOrder")
	proto.RegisterType((*Stock)(nil), "pb.Stock")
	proto.RegisterEnum("pb.CartChangeAction", CartChangeAction_name, CartChangeAction_value)
}

func init() { proto.RegisterFile("pkg/pb/products.proto", fileDescriptor_products_0baae3255f3d560b) }

var fileDescriptor_products_0baae3255f3d560b = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xd1, 0x6e, 0x94, 0x40,
	0x14, 0x85, 0xdd, 0x2e, 0xbb, 0x5c, 0x42, 0xbb, 0x9d, 0x54, 0x43, 0x9a, 0x98, 0xac, 0x68, 0x62,
	0x63, 0x74, 0x6b, 0xf0, 0xc1, 0xf8, 0xa8, 0xf8, 0x40, 0x13, 0x8d, 0x66, 0x4c, 0x3f, 0x60, 0x18,
	0x46, 0x4a, 0x96, 0x65, 0xc6, 0x61, 0xb0, 0xf6, 0x7b, 0xfd, 0x00, 0x7f, 0xa1, 0x99, 0x19, 0x4a,
	0xa1, 0xe9, 0x1b, 0xf7, 0x9c, 0x03, 0xe7, 0x9c, 0x3b, 0x03, 0x3c, 0x11, 0xbb, 0xf2, 0x5c, 0xe4,
	0xe7, 0x42, 0xf2, 0xa2, 0xa3, 0xaa, 0xdd, 0x0a, 0xc9, 0x15, 0x47, 0x33, 0x91, 0xc7, 0xff, 0x5d,
	0x58, 0xfe, 0xb0, 0x30, 0x42, 0x70, 0xd0, 0x75, 0x55, 0x11, 0xb9, 0x1b, 0xf7, 0xcc, 0xc7, 0xe6,
	0x19, 0x9d, 0xc0, 0x42, 0x55, 0xaa, 0x66, 0xd1, 0xcc, 0x80, 0x76, 0x40, 0x1b, 0x08, 0x0a, 0xd6,
	0x52, 0x59, 0x09, 0x55, 0xf1, 0x26, 0x9a, 0x1b, 0x6e, 0x0c, 0xa1, 0x53, 0x58, 0xd5, 0xbc, 0x29,
	0x15, 0xfb, 0xab, 0xa2, 0x03, 0x43, 0x0f, 0xb3, 0xe6, 0x28, 0x51, 0xac, 0xe4, 0xf2, 0x26, 0x5a,
	0x59, 0xee, 0x6e, 0x46, 0x2f, 0x21, 0x6c, 0xf7, 0xa4, 0xae, 0x2f, 0xf6, 0xa4, 0x64, 0x97, 0xf8,
	0x6b, 0xb4, 0x30, 0x82, 0x29, 0xa8, 0x55, 0x35, 0x91, 0x25, 0x1b, 0x54, 0x9e, 0x55, 0x4d, 0x40,
	0x9d, 0x5d, 0xc8, 0x8a, 0xb2, 0x68, 0xb9, 0x71, 0xcf, 0x66, 0xd8, 0x0e, 0xf1, 0x37, 0x08, 0xfb,
	0xc2, 0x97, 0xa2, 0x20, 0x8a, 0xa1, 0x67, 0x30, 0xe7, 0xb5, 0x6d, 0x1d, 0x24, 0xc1, 0x56, 0xe4,
	0xdb, 0x9e, 0xc7, 0x1a, 0xd7, 0x74, 0xc3, 0xae, 0x4d, 0xff, 0x87, 0x74, 0xc3, 0xae, 0xe3, 0x7f,
	0x2e, 0x1c, 0xa5, 0x57, 0x8c, 0xee, 0x78, 0xa7, 0x52, 0xde, 0x98, 0x82, 0xef, 0x00, 0x28, 0x91,
	0x2a, 0xbd, 0x22, 0x4d, 0xc9, 0xfa, 0x0f, 0x1f, 0xea, 0x37, 0xd3, 0x01, 0xcd, 0x1c, 0x3c, 0xd2,
	0xa0, 0xe7, 0xb0, 0x68, 0x15, 0xa7, 0xbb, 0xde, 0xc6, 0xd7, 0xe2, 0x9f, 0x1a, 0xc8, 0x1c, 0x6c,
	0x19, 0xf4, 0x11, 0x42, 0x31, 0xce, 0x6d, 0xb6, 0x1e, 0x24, 0xc7, 0xa3, 0x44, 0x96, 0xc8, 0x1c,
	0x3c, 0x55, 0xa2, 0xb7, 0xe0, 0x6b, 0xaf, 0xef, 0xb2, 0x60, 0xd2, 0x9c, 0x46, 0x90, 0x84, 0x77,
	0x71, 0x0c, 0x98, 0x39, 0xf8, 0x5e, 0xf1, 0xf9, 0x18, 0x8e, 0xe8, 0xb4, 0x51, 0xfc, 0x0b, 0xe0,
	0x3e, 0x3b, 0x7a, 0x0a, 0x9e, 0x56, 0x5f, 0x7c, 0xe9, 0x4f, 0xbe, 0x9f, 0x1e, 0xbd, 0x40, 0x6f,
	0xc0, 0x23, 0xd4, 0xdc, 0x12, 0x5d, 0xed, 0x30, 0x39, 0x99, 0xee, 0xe1, 0x93, 0xe1, 0x70, 0xaf,
	0x89, 0x5f, 0x80, 0x3f, 0x84, 0x1a, 0xd9, 0xb8, 0x63, 0x9b, 0xf8, 0x03, 0x2c, 0xcc, 0x6e, 0x1e,
	0xf5, 0x3b, 0x85, 0xd5, 0xef, 0x8e, 0x34, 0xaa, 0x52, 0x37, 0xc6, 0x11, 0xe1, 0x61, 0x7e, 0xfd,
	0x0a, 0xd6, 0x0f, 0x9d, 0xd1, 0x12, 0xe6, 0xa4, 0x28, 0xd6, 0x0e, 0x02, 0xf0, 0x24, 0xdb, 0xf3,
	0x3f, 0x6c, 0xed, 0xe6, 0x9e, 0xf9, 0x41, 0xde, 0xdf, 0x06, 0x00, 0x00, 0xff, 0xff, 0x54, 0x77,
	0x0e, 0xa9, 0x39, 0x03, 0x00, 0x00,
}
