// Code generated by protoc-gen-go. DO NOT EDIT.
// source: topic.proto

package checkout

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CheckoutMessages struct {
	// Types that are valid to be assigned to CheckoutMessage:
	//	*CheckoutMessages_ChangeProductQuantity
	//	*CheckoutMessages_StockCorrected
	//	*CheckoutMessages_Product
	//	*CheckoutMessages_OrderCart
	CheckoutMessage      isCheckoutMessages_CheckoutMessage `protobuf_oneof:"checkoutMessage"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *CheckoutMessages) Reset()         { *m = CheckoutMessages{} }
func (m *CheckoutMessages) String() string { return proto.CompactTextString(m) }
func (*CheckoutMessages) ProtoMessage()    {}
func (*CheckoutMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_topic_bdd3c7bac788a05a, []int{0}
}
func (m *CheckoutMessages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckoutMessages.Unmarshal(m, b)
}
func (m *CheckoutMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckoutMessages.Marshal(b, m, deterministic)
}
func (dst *CheckoutMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckoutMessages.Merge(dst, src)
}
func (m *CheckoutMessages) XXX_Size() int {
	return xxx_messageInfo_CheckoutMessages.Size(m)
}
func (m *CheckoutMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckoutMessages.DiscardUnknown(m)
}

var xxx_messageInfo_CheckoutMessages proto.InternalMessageInfo

type isCheckoutMessages_CheckoutMessage interface {
	isCheckoutMessages_CheckoutMessage()
}

type CheckoutMessages_ChangeProductQuantity struct {
	ChangeProductQuantity *ChangeProductQuantity `protobuf:"bytes,1,opt,name=changeProductQuantity,proto3,oneof"`
}

type CheckoutMessages_StockCorrected struct {
	StockCorrected *StockCorrected `protobuf:"bytes,2,opt,name=stockCorrected,proto3,oneof"`
}

type CheckoutMessages_Product struct {
	Product *Product `protobuf:"bytes,3,opt,name=product,proto3,oneof"`
}

type CheckoutMessages_OrderCart struct {
	OrderCart *OrderCart `protobuf:"bytes,4,opt,name=orderCart,proto3,oneof"`
}

func (*CheckoutMessages_ChangeProductQuantity) isCheckoutMessages_CheckoutMessage() {}

func (*CheckoutMessages_StockCorrected) isCheckoutMessages_CheckoutMessage() {}

func (*CheckoutMessages_Product) isCheckoutMessages_CheckoutMessage() {}

func (*CheckoutMessages_OrderCart) isCheckoutMessages_CheckoutMessage() {}

func (m *CheckoutMessages) GetCheckoutMessage() isCheckoutMessages_CheckoutMessage {
	if m != nil {
		return m.CheckoutMessage
	}
	return nil
}

func (m *CheckoutMessages) GetChangeProductQuantity() *ChangeProductQuantity {
	if x, ok := m.GetCheckoutMessage().(*CheckoutMessages_ChangeProductQuantity); ok {
		return x.ChangeProductQuantity
	}
	return nil
}

func (m *CheckoutMessages) GetStockCorrected() *StockCorrected {
	if x, ok := m.GetCheckoutMessage().(*CheckoutMessages_StockCorrected); ok {
		return x.StockCorrected
	}
	return nil
}

func (m *CheckoutMessages) GetProduct() *Product {
	if x, ok := m.GetCheckoutMessage().(*CheckoutMessages_Product); ok {
		return x.Product
	}
	return nil
}

func (m *CheckoutMessages) GetOrderCart() *OrderCart {
	if x, ok := m.GetCheckoutMessage().(*CheckoutMessages_OrderCart); ok {
		return x.OrderCart
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CheckoutMessages) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _CheckoutMessages_OneofMarshaler, _CheckoutMessages_OneofUnmarshaler, _CheckoutMessages_OneofSizer, []interface{}{
		(*CheckoutMessages_ChangeProductQuantity)(nil),
		(*CheckoutMessages_StockCorrected)(nil),
		(*CheckoutMessages_Product)(nil),
		(*CheckoutMessages_OrderCart)(nil),
	}
}

func _CheckoutMessages_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*CheckoutMessages)
	// checkoutMessage
	switch x := m.CheckoutMessage.(type) {
	case *CheckoutMessages_ChangeProductQuantity:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ChangeProductQuantity); err != nil {
			return err
		}
	case *CheckoutMessages_StockCorrected:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.StockCorrected); err != nil {
			return err
		}
	case *CheckoutMessages_Product:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Product); err != nil {
			return err
		}
	case *CheckoutMessages_OrderCart:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OrderCart); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("CheckoutMessages.CheckoutMessage has unexpected type %T", x)
	}
	return nil
}

func _CheckoutMessages_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*CheckoutMessages)
	switch tag {
	case 1: // checkoutMessage.changeProductQuantity
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ChangeProductQuantity)
		err := b.DecodeMessage(msg)
		m.CheckoutMessage = &CheckoutMessages_ChangeProductQuantity{msg}
		return true, err
	case 2: // checkoutMessage.stockCorrected
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StockCorrected)
		err := b.DecodeMessage(msg)
		m.CheckoutMessage = &CheckoutMessages_StockCorrected{msg}
		return true, err
	case 3: // checkoutMessage.product
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Product)
		err := b.DecodeMessage(msg)
		m.CheckoutMessage = &CheckoutMessages_Product{msg}
		return true, err
	case 4: // checkoutMessage.orderCart
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OrderCart)
		err := b.DecodeMessage(msg)
		m.CheckoutMessage = &CheckoutMessages_OrderCart{msg}
		return true, err
	default:
		return false, nil
	}
}

func _CheckoutMessages_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*CheckoutMessages)
	// checkoutMessage
	switch x := m.CheckoutMessage.(type) {
	case *CheckoutMessages_ChangeProductQuantity:
		s := proto.Size(x.ChangeProductQuantity)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CheckoutMessages_StockCorrected:
		s := proto.Size(x.StockCorrected)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CheckoutMessages_Product:
		s := proto.Size(x.Product)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CheckoutMessages_OrderCart:
		s := proto.Size(x.OrderCart)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ChangeProductQuantity struct {
	CartID               string   `protobuf:"bytes,3,opt,name=cartID,proto3" json:"cartID,omitempty"`
	ProductID            string   `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	Quantity             int64    `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeProductQuantity) Reset()         { *m = ChangeProductQuantity{} }
func (m *ChangeProductQuantity) String() string { return proto.CompactTextString(m) }
func (*ChangeProductQuantity) ProtoMessage()    {}
func (*ChangeProductQuantity) Descriptor() ([]byte, []int) {
	return fileDescriptor_topic_bdd3c7bac788a05a, []int{1}
}
func (m *ChangeProductQuantity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeProductQuantity.Unmarshal(m, b)
}
func (m *ChangeProductQuantity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeProductQuantity.Marshal(b, m, deterministic)
}
func (dst *ChangeProductQuantity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeProductQuantity.Merge(dst, src)
}
func (m *ChangeProductQuantity) XXX_Size() int {
	return xxx_messageInfo_ChangeProductQuantity.Size(m)
}
func (m *ChangeProductQuantity) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeProductQuantity.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeProductQuantity proto.InternalMessageInfo

func (m *ChangeProductQuantity) GetCartID() string {
	if m != nil {
		return m.CartID
	}
	return ""
}

func (m *ChangeProductQuantity) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *ChangeProductQuantity) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type StockCorrected struct {
	ProductID            string   `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	QuantityChange       int64    `protobuf:"varint,2,opt,name=quantityChange,proto3" json:"quantityChange,omitempty"`
	FulfilmentOffset     int64    `protobuf:"varint,3,opt,name=fulfilmentOffset,proto3" json:"fulfilmentOffset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockCorrected) Reset()         { *m = StockCorrected{} }
func (m *StockCorrected) String() string { return proto.CompactTextString(m) }
func (*StockCorrected) ProtoMessage()    {}
func (*StockCorrected) Descriptor() ([]byte, []int) {
	return fileDescriptor_topic_bdd3c7bac788a05a, []int{2}
}
func (m *StockCorrected) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockCorrected.Unmarshal(m, b)
}
func (m *StockCorrected) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockCorrected.Marshal(b, m, deterministic)
}
func (dst *StockCorrected) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockCorrected.Merge(dst, src)
}
func (m *StockCorrected) XXX_Size() int {
	return xxx_messageInfo_StockCorrected.Size(m)
}
func (m *StockCorrected) XXX_DiscardUnknown() {
	xxx_messageInfo_StockCorrected.DiscardUnknown(m)
}

var xxx_messageInfo_StockCorrected proto.InternalMessageInfo

func (m *StockCorrected) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *StockCorrected) GetQuantityChange() int64 {
	if m != nil {
		return m.QuantityChange
	}
	return 0
}

func (m *StockCorrected) GetFulfilmentOffset() int64 {
	if m != nil {
		return m.FulfilmentOffset
	}
	return 0
}

type Product struct {
	ProductID            string   `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	Price                int64    `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SmallImageURL        string   `protobuf:"bytes,4,opt,name=smallImageURL,proto3" json:"smallImageURL,omitempty"`
	PimOffset            int64    `protobuf:"varint,5,opt,name=pimOffset,proto3" json:"pimOffset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_topic_bdd3c7bac788a05a, []int{3}
}
func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (dst *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(dst, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *Product) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetSmallImageURL() string {
	if m != nil {
		return m.SmallImageURL
	}
	return ""
}

func (m *Product) GetPimOffset() int64 {
	if m != nil {
		return m.PimOffset
	}
	return 0
}

type OrderCart struct {
	CartID               string   `protobuf:"bytes,1,opt,name=cartID,proto3" json:"cartID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderCart) Reset()         { *m = OrderCart{} }
func (m *OrderCart) String() string { return proto.CompactTextString(m) }
func (*OrderCart) ProtoMessage()    {}
func (*OrderCart) Descriptor() ([]byte, []int) {
	return fileDescriptor_topic_bdd3c7bac788a05a, []int{4}
}
func (m *OrderCart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCart.Unmarshal(m, b)
}
func (m *OrderCart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCart.Marshal(b, m, deterministic)
}
func (dst *OrderCart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCart.Merge(dst, src)
}
func (m *OrderCart) XXX_Size() int {
	return xxx_messageInfo_OrderCart.Size(m)
}
func (m *OrderCart) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCart.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCart proto.InternalMessageInfo

func (m *OrderCart) GetCartID() string {
	if m != nil {
		return m.CartID
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckoutMessages)(nil), "checkout.CheckoutMessages")
	proto.RegisterType((*ChangeProductQuantity)(nil), "checkout.ChangeProductQuantity")
	proto.RegisterType((*StockCorrected)(nil), "checkout.StockCorrected")
	proto.RegisterType((*Product)(nil), "checkout.Product")
	proto.RegisterType((*OrderCart)(nil), "checkout.OrderCart")
}

func init() { proto.RegisterFile("topic.proto", fileDescriptor_topic_bdd3c7bac788a05a) }

var fileDescriptor_topic_bdd3c7bac788a05a = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcd, 0x4e, 0xeb, 0x30,
	0x10, 0x85, 0x93, 0xfe, 0x67, 0xaa, 0xdb, 0xdb, 0xfa, 0xde, 0xa2, 0x08, 0x21, 0x81, 0x02, 0x42,
	0x08, 0x89, 0x2e, 0xe8, 0x1b, 0x34, 0x5d, 0xa4, 0x12, 0xa8, 0x60, 0x84, 0x58, 0x1b, 0xd7, 0x69,
	0xa3, 0x26, 0x71, 0x70, 0x9c, 0x05, 0x5b, 0xde, 0x81, 0x57, 0xe0, 0x39, 0x11, 0x8e, 0xd3, 0x34,
	0xa5, 0x52, 0x77, 0x99, 0xe3, 0x39, 0x67, 0xc6, 0x9f, 0x03, 0x5d, 0xc9, 0x93, 0x80, 0x8e, 0x12,
	0xc1, 0x25, 0x47, 0x1d, 0xba, 0x62, 0x74, 0xcd, 0x33, 0xe9, 0x7c, 0xd5, 0xa0, 0xef, 0xea, 0xe2,
	0x9e, 0xa5, 0x29, 0x59, 0xb2, 0x14, 0xbd, 0xc0, 0x90, 0xae, 0x48, 0xbc, 0x64, 0x0f, 0x82, 0x2f,
	0x32, 0x2a, 0x1f, 0x33, 0x12, 0xcb, 0x40, 0xbe, 0xdb, 0xe6, 0x99, 0x79, 0xd5, 0xbd, 0x3d, 0x1d,
	0x15, 0xf6, 0x91, 0xbb, 0xaf, 0xcd, 0x33, 0xf0, 0x7e, 0x3f, 0x9a, 0x40, 0x2f, 0x95, 0x9c, 0xae,
	0x5d, 0x2e, 0x04, 0xa3, 0x92, 0x2d, 0xec, 0x9a, 0x4a, 0xb4, 0xcb, 0xc4, 0xa7, 0xca, 0xb9, 0x67,
	0xe0, 0x1d, 0x07, 0xba, 0x81, 0x76, 0x92, 0xc7, 0xda, 0x75, 0x65, 0x1e, 0x94, 0x66, 0x3d, 0xcf,
	0x33, 0x70, 0xd1, 0x83, 0xc6, 0x60, 0x71, 0xb1, 0x60, 0xc2, 0x25, 0x42, 0xda, 0x0d, 0x65, 0xf8,
	0x57, 0x1a, 0xe6, 0xc5, 0x91, 0x67, 0xe0, 0xb2, 0x6f, 0x32, 0x80, 0xbf, 0xb4, 0x0a, 0xc5, 0x09,
	0x60, 0xb8, 0xf7, 0xb2, 0xe8, 0x08, 0x5a, 0x94, 0x08, 0x39, 0x9b, 0xaa, 0x75, 0x2c, 0xac, 0x2b,
	0x74, 0x02, 0x96, 0xde, 0x61, 0x36, 0x55, 0xe0, 0x2c, 0x5c, 0x0a, 0xe8, 0x18, 0x3a, 0x6f, 0x05,
	0xd5, 0x1f, 0x06, 0x75, 0xbc, 0xa9, 0x9d, 0x0f, 0x13, 0x7a, 0x55, 0x0c, 0x07, 0xc2, 0x2e, 0xa1,
	0x57, 0x98, 0xf3, 0x1d, 0x75, 0xe4, 0x8e, 0x8a, 0xae, 0xa1, 0xef, 0x67, 0xa1, 0x1f, 0x84, 0x11,
	0x8b, 0xe5, 0xdc, 0xf7, 0x53, 0x96, 0x33, 0xac, 0xe3, 0x5f, 0xba, 0xf3, 0x69, 0x42, 0x5b, 0x5f,
	0xf5, 0xc0, 0xf4, 0xff, 0xd0, 0x4c, 0x44, 0x40, 0x8b, 0xa1, 0x79, 0x81, 0x10, 0x34, 0x62, 0x12,
	0x31, 0x0d, 0x45, 0x7d, 0xa3, 0x0b, 0xf8, 0x93, 0x46, 0x24, 0x0c, 0x67, 0x11, 0x59, 0xb2, 0x67,
	0x7c, 0xa7, 0xde, 0xc3, 0xc2, 0x55, 0x51, 0x4d, 0x0b, 0x22, 0xbd, 0x5e, 0x53, 0x65, 0x96, 0x82,
	0x73, 0x0e, 0xd6, 0xe6, 0xd1, 0xb6, 0xd8, 0x9b, 0xdb, 0xec, 0x5f, 0x5b, 0xea, 0x37, 0x1f, 0x7f,
	0x07, 0x00, 0x00, 0xff, 0xff, 0xf1, 0xee, 0xe0, 0x1e, 0xf5, 0x02, 0x00, 0x00,
}
