// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package checkout

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Cart struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Positions            []*Position `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Cart) Reset()         { *m = Cart{} }
func (m *Cart) String() string { return proto.CompactTextString(m) }
func (*Cart) ProtoMessage()    {}
func (*Cart) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Cart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cart.Unmarshal(m, b)
}
func (m *Cart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cart.Marshal(b, m, deterministic)
}
func (m *Cart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cart.Merge(m, src)
}
func (m *Cart) XXX_Size() int {
	return xxx_messageInfo_Cart.Size(m)
}
func (m *Cart) XXX_DiscardUnknown() {
	xxx_messageInfo_Cart.DiscardUnknown(m)
}

var xxx_messageInfo_Cart proto.InternalMessageInfo

func (m *Cart) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Cart) GetPositions() []*Position {
	if m != nil {
		return m.Positions
	}
	return nil
}

type Position struct {
	ProductID            string   `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	Price                int64    `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SmallImageURL        string   `protobuf:"bytes,4,opt,name=smallImageURL,proto3" json:"smallImageURL,omitempty"`
	Quantity             int64    `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	InStock              bool     `protobuf:"varint,7,opt,name=inStock,proto3" json:"inStock,omitempty"`
	MoreInStock          bool     `protobuf:"varint,8,opt,name=moreInStock,proto3" json:"moreInStock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *Position) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Position) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Position) GetSmallImageURL() string {
	if m != nil {
		return m.SmallImageURL
	}
	return ""
}

func (m *Position) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Position) GetInStock() bool {
	if m != nil {
		return m.InStock
	}
	return false
}

func (m *Position) GetMoreInStock() bool {
	if m != nil {
		return m.MoreInStock
	}
	return false
}

type OrderCartResonse struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderCartResonse) Reset()         { *m = OrderCartResonse{} }
func (m *OrderCartResonse) String() string { return proto.CompactTextString(m) }
func (*OrderCartResonse) ProtoMessage()    {}
func (*OrderCartResonse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *OrderCartResonse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCartResonse.Unmarshal(m, b)
}
func (m *OrderCartResonse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCartResonse.Marshal(b, m, deterministic)
}
func (m *OrderCartResonse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCartResonse.Merge(m, src)
}
func (m *OrderCartResonse) XXX_Size() int {
	return xxx_messageInfo_OrderCartResonse.Size(m)
}
func (m *OrderCartResonse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCartResonse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCartResonse proto.InternalMessageInfo

func (m *OrderCartResonse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

func init() {
	proto.RegisterType((*Cart)(nil), "checkout.Cart")
	proto.RegisterType((*Position)(nil), "checkout.Position")
	proto.RegisterType((*OrderCartResonse)(nil), "checkout.OrderCartResonse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcd, 0x4a, 0xf4, 0x30,
	0x14, 0x86, 0xe9, 0xcf, 0x37, 0x93, 0x9e, 0xe1, 0x13, 0x39, 0xb8, 0x08, 0x22, 0x52, 0x8a, 0x8b,
	0xae, 0x8a, 0x8c, 0x97, 0xa0, 0x0b, 0x0b, 0x82, 0x12, 0xf1, 0x02, 0x62, 0x1a, 0x35, 0x4c, 0x9b,
	0xc4, 0xfc, 0x2c, 0xbc, 0x4b, 0x2f, 0x49, 0x8c, 0xad, 0x33, 0xee, 0xf2, 0x3e, 0xcf, 0xc9, 0x81,
	0xf3, 0x42, 0xc5, 0xad, 0xea, 0xac, 0x33, 0xc1, 0x20, 0x11, 0x6f, 0x52, 0xec, 0x4c, 0x0c, 0xcd,
	0x2d, 0x94, 0xd7, 0xdc, 0x05, 0x3c, 0x82, 0x5c, 0x0d, 0x34, 0xab, 0xb3, 0xb6, 0x62, 0xb9, 0x1a,
	0xf0, 0x12, 0x2a, 0x6b, 0xbc, 0x0a, 0xca, 0x68, 0x4f, 0xf3, 0xba, 0x68, 0x37, 0x5b, 0xec, 0x96,
	0x5f, 0xdd, 0xc3, 0xac, 0xd8, 0x7e, 0xa8, 0xf9, 0xcc, 0x80, 0x2c, 0x1c, 0xcf, 0xa0, 0xb2, 0xce,
	0x0c, 0x51, 0x84, 0xfe, 0x66, 0xde, 0xba, 0x07, 0x78, 0x02, 0xff, 0xac, 0x53, 0x42, 0xd2, 0xbc,
	0xce, 0xda, 0x82, 0xfd, 0x04, 0x44, 0x28, 0x35, 0x9f, 0x24, 0x2d, 0xd2, 0x78, 0x7a, 0xe3, 0x05,
	0xfc, 0xf7, 0x13, 0x1f, 0xc7, 0x7e, 0xe2, 0xaf, 0xf2, 0x89, 0xdd, 0xd1, 0x32, 0xc9, 0xbf, 0x10,
	0x4f, 0x81, 0xbc, 0x47, 0xae, 0x83, 0x0a, 0x1f, 0x74, 0x95, 0x56, 0xfe, 0x66, 0xa4, 0xb0, 0x56,
	0xfa, 0x31, 0x18, 0xb1, 0xa3, 0xeb, 0x3a, 0x6b, 0x09, 0x5b, 0x22, 0xd6, 0xb0, 0x99, 0x8c, 0x93,
	0xfd, 0x6c, 0x49, 0xb2, 0x87, 0xa8, 0xd9, 0xc2, 0xf1, 0xbd, 0x1b, 0xa4, 0xfb, 0x6e, 0x88, 0x49,
	0x6f, 0xb4, 0x97, 0x78, 0x0e, 0xe0, 0xa3, 0x10, 0xd2, 0xfb, 0x97, 0x38, 0xa6, 0xd3, 0x08, 0x3b,
	0x20, 0xcf, 0xab, 0xd4, 0xf0, 0xd5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x46, 0x52, 0x02, 0xe6,
	0x6e, 0x01, 0x00, 0x00,
}
