// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pim.proto

package pim

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PimMessages struct {
	// Types that are valid to be assigned to PimMessage:
	//	*PimMessages_Product
	PimMessage           isPimMessages_PimMessage `protobuf_oneof:"pimMessage"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *PimMessages) Reset()         { *m = PimMessages{} }
func (m *PimMessages) String() string { return proto.CompactTextString(m) }
func (*PimMessages) ProtoMessage()    {}
func (*PimMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_pim_4e1b9d42e8b389d2, []int{0}
}
func (m *PimMessages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PimMessages.Unmarshal(m, b)
}
func (m *PimMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PimMessages.Marshal(b, m, deterministic)
}
func (dst *PimMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PimMessages.Merge(dst, src)
}
func (m *PimMessages) XXX_Size() int {
	return xxx_messageInfo_PimMessages.Size(m)
}
func (m *PimMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_PimMessages.DiscardUnknown(m)
}

var xxx_messageInfo_PimMessages proto.InternalMessageInfo

type isPimMessages_PimMessage interface {
	isPimMessages_PimMessage()
}

type PimMessages_Product struct {
	Product *Product `protobuf:"bytes,1,opt,name=product,proto3,oneof"`
}

func (*PimMessages_Product) isPimMessages_PimMessage() {}

func (m *PimMessages) GetPimMessage() isPimMessages_PimMessage {
	if m != nil {
		return m.PimMessage
	}
	return nil
}

func (m *PimMessages) GetProduct() *Product {
	if x, ok := m.GetPimMessage().(*PimMessages_Product); ok {
		return x.Product
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PimMessages) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PimMessages_OneofMarshaler, _PimMessages_OneofUnmarshaler, _PimMessages_OneofSizer, []interface{}{
		(*PimMessages_Product)(nil),
	}
}

func _PimMessages_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PimMessages)
	// pimMessage
	switch x := m.PimMessage.(type) {
	case *PimMessages_Product:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Product); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("PimMessages.PimMessage has unexpected type %T", x)
	}
	return nil
}

func _PimMessages_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PimMessages)
	switch tag {
	case 1: // pimMessage.product
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Product)
		err := b.DecodeMessage(msg)
		m.PimMessage = &PimMessages_Product{msg}
		return true, err
	default:
		return false, nil
	}
}

func _PimMessages_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PimMessages)
	// pimMessage
	switch x := m.PimMessage.(type) {
	case *PimMessages_Product:
		s := proto.Size(x.Product)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price                int64    `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Longtext             string   `protobuf:"bytes,5,opt,name=longtext,proto3" json:"longtext,omitempty"`
	Category             string   `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	SmallImageURL        string   `protobuf:"bytes,7,opt,name=smallImageURL,proto3" json:"smallImageURL,omitempty"`
	LargeImageURL        string   `protobuf:"bytes,8,opt,name=largeImageURL,proto3" json:"largeImageURL,omitempty"`
	Disabled             bool     `protobuf:"varint,9,opt,name=disabled,proto3" json:"disabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_pim_4e1b9d42e8b389d2, []int{1}
}
func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (dst *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(dst, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetLongtext() string {
	if m != nil {
		return m.Longtext
	}
	return ""
}

func (m *Product) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Product) GetSmallImageURL() string {
	if m != nil {
		return m.SmallImageURL
	}
	return ""
}

func (m *Product) GetLargeImageURL() string {
	if m != nil {
		return m.LargeImageURL
	}
	return ""
}

func (m *Product) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func init() {
	proto.RegisterType((*PimMessages)(nil), "pim.PimMessages")
	proto.RegisterType((*Product)(nil), "pim.Product")
}

func init() { proto.RegisterFile("pim.proto", fileDescriptor_pim_4e1b9d42e8b389d2) }

var fileDescriptor_pim_4e1b9d42e8b389d2 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x85, 0x6d, 0xe7, 0xa7, 0xed, 0xed, 0xe8, 0x22, 0xb8, 0x08, 0xae, 0xca, 0xe0, 0xa2, 0xab,
	0x59, 0xe8, 0x1b, 0x08, 0x82, 0x82, 0xc2, 0x10, 0xf0, 0x01, 0x32, 0xcd, 0x25, 0x5c, 0x48, 0x9a,
	0x90, 0x44, 0xd0, 0x07, 0xf0, 0xbd, 0xa5, 0xa9, 0x53, 0x9c, 0x5d, 0xce, 0xf9, 0xbe, 0x43, 0xe0,
	0x42, 0xe3, 0xc9, 0x1e, 0x7c, 0x70, 0xc9, 0xb1, 0x95, 0x27, 0xbb, 0x7f, 0x86, 0xf6, 0x48, 0xf6,
	0x1d, 0x63, 0x94, 0x1a, 0x23, 0xeb, 0xa1, 0xf2, 0xc1, 0xa9, 0xcf, 0x21, 0xf1, 0xa2, 0x2b, 0xfa,
	0xf6, 0x61, 0x77, 0x98, 0x06, 0xc7, 0xb9, 0x7b, 0xb9, 0x12, 0x67, 0xfc, 0xb4, 0x03, 0xf0, 0xcb,
	0x70, 0xff, 0x53, 0x42, 0xf5, 0x27, 0xb1, 0x1b, 0x28, 0x49, 0xe5, 0x79, 0x23, 0x4a, 0x52, 0xec,
	0x16, 0x36, 0x3e, 0xd0, 0x80, 0xbc, 0xec, 0x8a, 0x7e, 0x25, 0xe6, 0xc0, 0x18, 0xac, 0x47, 0x69,
	0x91, 0xaf, 0xb2, 0x97, 0xdf, 0xac, 0x83, 0x56, 0x61, 0x1c, 0x02, 0xf9, 0x44, 0x6e, 0xe4, 0xeb,
	0x8c, 0xfe, 0x57, 0xec, 0x0e, 0x6a, 0xe3, 0x46, 0x9d, 0xf0, 0x2b, 0xf1, 0x4d, 0xc6, 0x4b, 0x9e,
	0xd8, 0x20, 0x13, 0x6a, 0x17, 0xbe, 0xf9, 0x76, 0x66, 0xe7, 0xcc, 0xee, 0xe1, 0x3a, 0x5a, 0x69,
	0xcc, 0xab, 0x95, 0x1a, 0x3f, 0xc4, 0x1b, 0xaf, 0xb2, 0x70, 0x59, 0x4e, 0x96, 0x91, 0x41, 0xe3,
	0x62, 0xd5, 0xb3, 0x75, 0x51, 0x4e, 0xff, 0x28, 0x8a, 0xf2, 0x64, 0x50, 0xf1, 0xa6, 0x2b, 0xfa,
	0x5a, 0x2c, 0xf9, 0xb4, 0xcd, 0xa7, 0x7d, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x3f, 0x20,
	0xdb, 0x67, 0x01, 0x00, 0x00,
}
