// Code generated by simba. DO NOT EDIT.

package {{ .Name }}

import (
	"fmt"

	"github.com/Shopify/sarama"
	"github.com/golang/protobuf/proto"
)

{{ range .MessageNames }}
func (c *context) produce{{ . | title }}(logMsg *{{ . | title }}) (int32, int64, error) {

	msg := &TopicMessage{
		Messages: &TopicMessage_{{ . | title }}{
			{{ . | title }}: logMsg,
		},
	}

	bytes, err := proto.Marshal(msg)
	if err != nil {
		return 0, 0, fmt.Errorf("failed to serialize {{ . }} change massage: %v", err)
	}

	return c.producer.SendMessage(&sarama.ProducerMessage{ Topic: Topic, Value: sarama.ByteEncoder(bytes) })
}

func (c *context) produceAsync{{ . | title }}(logMsg *{{ . | title }}) error {

	msg := &TopicMessage{
		Messages: &TopicMessage_{{ . | title }}{
			{{ . | title }}: logMsg,
		},
	}

	bytes, err := proto.Marshal(msg)
	if err != nil {
		return fmt.Errorf("failed to serialize {{ . }} change massage: %v", err)
	}

	c.producer.Input() <- &sarama.ProducerMessage{ Topic: Topic, Value: sarama.ByteEncoder(bytes) }

	return nil
}
{{ end }}
