// Code generated by simba. DO NOT EDIT.

package {{ .Name }}

import (
	"fmt"

	"github.com/Shopify/sarama"
	"github.com/golang/protobuf/proto"
)

type asyncProducer struct {
	sarama.AsyncProducer
}

func (c *context) newSyncProducer() (asyncProducer, error) {
	producer, err := sarama.NewAsyncProducerFromClient(c.client)
	if err != nil {
		return asyncProducer{}, fmt.Errorf("failed to create async producer: %v", err)
	}
	return asyncProducer{
		AsyncProducer: producer,
	}, nil
}

func (p *asyncProducer) awaitClose(f func(error)) sync.WaitGroup {
	var wg sync.WaitGroup
	wg.Add(1)
	go func() {
		for err := range p.Errors() {
			f(err)
		}
		wg.Done()
	}()
	wg.Add(1)
	go func() {
		for _ = range p.Successes() {
		}
		wg.Done()
	}()
	return wg
}

{{ range .MessageNames }}
func (c *context) append{{ . | title }}(msg *{{ . | title }}) (int32, int64, error) {

	topicMsg := &TopicMessage{
		Messages: &TopicMessage_{{ . | title }}{
			{{ . | title }}: msg,
		},
	}

	bytes, err := proto.Marshal(topicMsg)
	if err != nil {
		return 0, 0, fmt.Errorf("failed to serialize {{ . }} change massage: %v", err)
	}

	producerMsg := &sarama.ProducerMessage{
		Topic: Topic,
		Value: sarama.ByteEncoder(bytes),
	}
	return c.producer.SendMessage(producerMsg)
}

func (p asyncProducer) append{{ . | title }}(msg *{{ . | title }}) error {

	topicMsg := &TopicMessage{
		Messages: &TopicMessage_{{ . | title }}{
			{{ . | title }}: msg,
		},
	}

	bytes, err := proto.Marshal(topicMsg)
	if err != nil {
		return fmt.Errorf("failed to serialize {{ . }} change massage: %v", err)
	}

	producerMsg := &sarama.ProducerMessage{
		Topic: Topic,
		Value: sarama.ByteEncoder(bytes),
	}
	p.Input() <- producerMsg

	return nil
}
{{ end }}
