{-
   api.proto
   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   The version of the OpenAPI document: version not set

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.CatalogProductResponse exposing (CatalogProductResponse, decoder, encode)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias CatalogProductResponse =
    { id : Maybe (String)
    , price : Maybe (String)
    , name : Maybe (String)
    , description : Maybe (String)
    , longtext : Maybe (String)
    , category : Maybe (String)
    , smallImageURL : Maybe (String)
    , largeImageURL : Maybe (String)
    , disabled : Maybe (Bool)
    }


decoder : Decoder CatalogProductResponse
decoder =
    Decode.succeed CatalogProductResponse
        |> optional "id" (Decode.nullable Decode.string) Nothing
        |> optional "price" (Decode.nullable Decode.string) Nothing
        |> optional "name" (Decode.nullable Decode.string) Nothing
        |> optional "description" (Decode.nullable Decode.string) Nothing
        |> optional "longtext" (Decode.nullable Decode.string) Nothing
        |> optional "category" (Decode.nullable Decode.string) Nothing
        |> optional "smallImageURL" (Decode.nullable Decode.string) Nothing
        |> optional "largeImageURL" (Decode.nullable Decode.string) Nothing
        |> optional "disabled" (Decode.nullable Decode.bool) Nothing



encode : CatalogProductResponse -> Encode.Value
encode model =
    Encode.object
        [ ( "id", Maybe.withDefault Encode.null (Maybe.map Encode.string model.id) )
        , ( "price", Maybe.withDefault Encode.null (Maybe.map Encode.string model.price) )
        , ( "name", Maybe.withDefault Encode.null (Maybe.map Encode.string model.name) )
        , ( "description", Maybe.withDefault Encode.null (Maybe.map Encode.string model.description) )
        , ( "longtext", Maybe.withDefault Encode.null (Maybe.map Encode.string model.longtext) )
        , ( "category", Maybe.withDefault Encode.null (Maybe.map Encode.string model.category) )
        , ( "smallImageURL", Maybe.withDefault Encode.null (Maybe.map Encode.string model.smallImageURL) )
        , ( "largeImageURL", Maybe.withDefault Encode.null (Maybe.map Encode.string model.largeImageURL) )
        , ( "disabled", Maybe.withDefault Encode.null (Maybe.map Encode.bool model.disabled) )

        ]


