{-
   api.proto
   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   The version of the OpenAPI document: version not set

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.CatalogCatalogRequest exposing (CatalogCatalogRequest, decoder, encode)

import Data.CatalogRequestSorting as CatalogRequestSorting exposing (CatalogRequestSorting)
import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias CatalogCatalogRequest =
    { sorting : Maybe (CatalogRequestSorting)
    , prefix : Maybe (String)
    , page : Maybe (String)
    , itemsPerPage : Maybe (String)
    }


decoder : Decoder CatalogCatalogRequest
decoder =
    Decode.succeed CatalogCatalogRequest
        |> optional "sorting" (Decode.nullable CatalogRequestSorting.decoder) Nothing
        |> optional "prefix" (Decode.nullable Decode.string) Nothing
        |> optional "page" (Decode.nullable Decode.string) Nothing
        |> optional "itemsPerPage" (Decode.nullable Decode.string) Nothing



encode : CatalogCatalogRequest -> Encode.Value
encode model =
    Encode.object
        [ ( "sorting", Maybe.withDefault Encode.null (Maybe.map CatalogRequestSorting.encode model.sorting) )
        , ( "prefix", Maybe.withDefault Encode.null (Maybe.map Encode.string model.prefix) )
        , ( "page", Maybe.withDefault Encode.null (Maybe.map Encode.string model.page) )
        , ( "itemsPerPage", Maybe.withDefault Encode.null (Maybe.map Encode.string model.itemsPerPage) )

        ]


