{-
   api.proto
   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   The version of the OpenAPI document: version not set

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.CatalogRequestSorting exposing (CatalogRequestSorting(..), decoder, encode)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type CatalogRequestSorting
    = ID
    | PRICE
    | NAME



decoder : Decoder CatalogRequestSorting
decoder =
    Decode.string
        |> Decode.andThen
            (\str ->
                case str of
                    "ID" ->
                        Decode.succeed ID

                    "PRICE" ->
                        Decode.succeed PRICE

                    "NAME" ->
                        Decode.succeed NAME

                    other ->
                        Decode.fail <| "Unknown type: " ++ other
            )



encode : CatalogRequestSorting -> Encode.Value
encode model =
    case model of
        ID ->
            Encode.string "ID"

        PRICE ->
            Encode.string "PRICE"

        NAME ->
            Encode.string "NAME"


