// Code generated by protoc-gen-go. DO NOT EDIT.
// source: topic.proto

package topic

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FulfilmentMessages struct {
	// Types that are valid to be assigned to FulfilmentMessage:
	//	*FulfilmentMessages_StockCorrected
	FulfilmentMessage    isFulfilmentMessages_FulfilmentMessage `protobuf_oneof:"fulfilmentMessage"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *FulfilmentMessages) Reset()         { *m = FulfilmentMessages{} }
func (m *FulfilmentMessages) String() string { return proto.CompactTextString(m) }
func (*FulfilmentMessages) ProtoMessage()    {}
func (*FulfilmentMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_topic_25e8afdde845dc47, []int{0}
}
func (m *FulfilmentMessages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FulfilmentMessages.Unmarshal(m, b)
}
func (m *FulfilmentMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FulfilmentMessages.Marshal(b, m, deterministic)
}
func (dst *FulfilmentMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FulfilmentMessages.Merge(dst, src)
}
func (m *FulfilmentMessages) XXX_Size() int {
	return xxx_messageInfo_FulfilmentMessages.Size(m)
}
func (m *FulfilmentMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_FulfilmentMessages.DiscardUnknown(m)
}

var xxx_messageInfo_FulfilmentMessages proto.InternalMessageInfo

type isFulfilmentMessages_FulfilmentMessage interface {
	isFulfilmentMessages_FulfilmentMessage()
}

type FulfilmentMessages_StockCorrected struct {
	StockCorrected *StockCorrected `protobuf:"bytes,1,opt,name=stockCorrected,proto3,oneof"`
}

func (*FulfilmentMessages_StockCorrected) isFulfilmentMessages_FulfilmentMessage() {}

func (m *FulfilmentMessages) GetFulfilmentMessage() isFulfilmentMessages_FulfilmentMessage {
	if m != nil {
		return m.FulfilmentMessage
	}
	return nil
}

func (m *FulfilmentMessages) GetStockCorrected() *StockCorrected {
	if x, ok := m.GetFulfilmentMessage().(*FulfilmentMessages_StockCorrected); ok {
		return x.StockCorrected
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*FulfilmentMessages) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _FulfilmentMessages_OneofMarshaler, _FulfilmentMessages_OneofUnmarshaler, _FulfilmentMessages_OneofSizer, []interface{}{
		(*FulfilmentMessages_StockCorrected)(nil),
	}
}

func _FulfilmentMessages_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*FulfilmentMessages)
	// fulfilmentMessage
	switch x := m.FulfilmentMessage.(type) {
	case *FulfilmentMessages_StockCorrected:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.StockCorrected); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("FulfilmentMessages.FulfilmentMessage has unexpected type %T", x)
	}
	return nil
}

func _FulfilmentMessages_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*FulfilmentMessages)
	switch tag {
	case 1: // fulfilmentMessage.stockCorrected
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StockCorrected)
		err := b.DecodeMessage(msg)
		m.FulfilmentMessage = &FulfilmentMessages_StockCorrected{msg}
		return true, err
	default:
		return false, nil
	}
}

func _FulfilmentMessages_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*FulfilmentMessages)
	// fulfilmentMessage
	switch x := m.FulfilmentMessage.(type) {
	case *FulfilmentMessages_StockCorrected:
		s := proto.Size(x.StockCorrected)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type StockCorrected struct {
	ProductID            string   `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	QuantityChange       int64    `protobuf:"varint,2,opt,name=quantityChange,proto3" json:"quantityChange,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockCorrected) Reset()         { *m = StockCorrected{} }
func (m *StockCorrected) String() string { return proto.CompactTextString(m) }
func (*StockCorrected) ProtoMessage()    {}
func (*StockCorrected) Descriptor() ([]byte, []int) {
	return fileDescriptor_topic_25e8afdde845dc47, []int{1}
}
func (m *StockCorrected) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockCorrected.Unmarshal(m, b)
}
func (m *StockCorrected) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockCorrected.Marshal(b, m, deterministic)
}
func (dst *StockCorrected) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockCorrected.Merge(dst, src)
}
func (m *StockCorrected) XXX_Size() int {
	return xxx_messageInfo_StockCorrected.Size(m)
}
func (m *StockCorrected) XXX_DiscardUnknown() {
	xxx_messageInfo_StockCorrected.DiscardUnknown(m)
}

var xxx_messageInfo_StockCorrected proto.InternalMessageInfo

func (m *StockCorrected) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *StockCorrected) GetQuantityChange() int64 {
	if m != nil {
		return m.QuantityChange
	}
	return 0
}

func init() {
	proto.RegisterType((*FulfilmentMessages)(nil), "FulfilmentMessages")
	proto.RegisterType((*StockCorrected)(nil), "StockCorrected")
}

func init() { proto.RegisterFile("topic.proto", fileDescriptor_topic_25e8afdde845dc47) }

var fileDescriptor_topic_25e8afdde845dc47 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xc9, 0x2f, 0xc8,
	0x4c, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x4a, 0xe1, 0x12, 0x72, 0x2b, 0xcd, 0x49, 0xcb,
	0xcc, 0xc9, 0x4d, 0xcd, 0x2b, 0xf1, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x2d, 0x16, 0xb2, 0xe4,
	0xe2, 0x2b, 0x2e, 0xc9, 0x4f, 0xce, 0x76, 0xce, 0x2f, 0x2a, 0x4a, 0x4d, 0x2e, 0x49, 0x4d, 0x91,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x36, 0xe2, 0xd7, 0x0b, 0x46, 0x11, 0xf6, 0x60, 0x08, 0x42, 0x53,
	0xe8, 0x24, 0xcc, 0x25, 0x98, 0x86, 0x6e, 0xa0, 0x52, 0x18, 0x17, 0x1f, 0xaa, 0x46, 0x21, 0x19,
	0x2e, 0xce, 0x82, 0xa2, 0xfc, 0x94, 0xd2, 0xe4, 0x12, 0x4f, 0x17, 0xb0, 0xe1, 0x9c, 0x41, 0x08,
	0x01, 0x21, 0x35, 0x2e, 0xbe, 0xc2, 0xd2, 0xc4, 0xbc, 0x92, 0xcc, 0x92, 0x4a, 0xe7, 0x8c, 0xc4,
	0xbc, 0xf4, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x34, 0xd1, 0x24, 0x36, 0xb0, 0x27,
	0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xea, 0x1f, 0x56, 0xa6, 0xd3, 0x00, 0x00, 0x00,
}
