// Code generated by protoc-gen-go. DO NOT EDIT.
// source: catalog.proto

package catalog

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CatalogMessages struct {
	// Types that are valid to be assigned to CatalogMessage:
	//	*CatalogMessages_Product
	CatalogMessage       isCatalogMessages_CatalogMessage `protobuf_oneof:"catalogMessage"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *CatalogMessages) Reset()         { *m = CatalogMessages{} }
func (m *CatalogMessages) String() string { return proto.CompactTextString(m) }
func (*CatalogMessages) ProtoMessage()    {}
func (*CatalogMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_catalog_356a75a4028f7efd, []int{0}
}
func (m *CatalogMessages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CatalogMessages.Unmarshal(m, b)
}
func (m *CatalogMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CatalogMessages.Marshal(b, m, deterministic)
}
func (dst *CatalogMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CatalogMessages.Merge(dst, src)
}
func (m *CatalogMessages) XXX_Size() int {
	return xxx_messageInfo_CatalogMessages.Size(m)
}
func (m *CatalogMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_CatalogMessages.DiscardUnknown(m)
}

var xxx_messageInfo_CatalogMessages proto.InternalMessageInfo

type isCatalogMessages_CatalogMessage interface {
	isCatalogMessages_CatalogMessage()
}

type CatalogMessages_Product struct {
	Product *Product `protobuf:"bytes,1,opt,name=product,proto3,oneof"`
}

func (*CatalogMessages_Product) isCatalogMessages_CatalogMessage() {}

func (m *CatalogMessages) GetCatalogMessage() isCatalogMessages_CatalogMessage {
	if m != nil {
		return m.CatalogMessage
	}
	return nil
}

func (m *CatalogMessages) GetProduct() *Product {
	if x, ok := m.GetCatalogMessage().(*CatalogMessages_Product); ok {
		return x.Product
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CatalogMessages) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _CatalogMessages_OneofMarshaler, _CatalogMessages_OneofUnmarshaler, _CatalogMessages_OneofSizer, []interface{}{
		(*CatalogMessages_Product)(nil),
	}
}

func _CatalogMessages_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*CatalogMessages)
	// catalogMessage
	switch x := m.CatalogMessage.(type) {
	case *CatalogMessages_Product:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Product); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("CatalogMessages.CatalogMessage has unexpected type %T", x)
	}
	return nil
}

func _CatalogMessages_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*CatalogMessages)
	switch tag {
	case 1: // catalogMessage.product
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Product)
		err := b.DecodeMessage(msg)
		m.CatalogMessage = &CatalogMessages_Product{msg}
		return true, err
	default:
		return false, nil
	}
}

func _CatalogMessages_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*CatalogMessages)
	// catalogMessage
	switch x := m.CatalogMessage.(type) {
	case *CatalogMessages_Product:
		s := proto.Size(x.Product)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type CatalogPage struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	TotalItems           int64      `protobuf:"varint,2,opt,name=totalItems,proto3" json:"totalItems,omitempty"`
	TotalPages           int64      `protobuf:"varint,3,opt,name=totalPages,proto3" json:"totalPages,omitempty"`
	CurrentPage          int64      `protobuf:"varint,4,opt,name=currentPage,proto3" json:"currentPage,omitempty"`
	SetPageTo            int64      `protobuf:"varint,5,opt,name=setPageTo,proto3" json:"setPageTo,omitempty"`
	Sorting              string     `protobuf:"bytes,6,opt,name=sorting,proto3" json:"sorting,omitempty"`
	Filtering            string     `protobuf:"bytes,7,opt,name=filtering,proto3" json:"filtering,omitempty"`
	ItemsPerPage         int64      `protobuf:"varint,8,opt,name=itemsPerPage,proto3" json:"itemsPerPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CatalogPage) Reset()         { *m = CatalogPage{} }
func (m *CatalogPage) String() string { return proto.CompactTextString(m) }
func (*CatalogPage) ProtoMessage()    {}
func (*CatalogPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_catalog_356a75a4028f7efd, []int{1}
}
func (m *CatalogPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CatalogPage.Unmarshal(m, b)
}
func (m *CatalogPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CatalogPage.Marshal(b, m, deterministic)
}
func (dst *CatalogPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CatalogPage.Merge(dst, src)
}
func (m *CatalogPage) XXX_Size() int {
	return xxx_messageInfo_CatalogPage.Size(m)
}
func (m *CatalogPage) XXX_DiscardUnknown() {
	xxx_messageInfo_CatalogPage.DiscardUnknown(m)
}

var xxx_messageInfo_CatalogPage proto.InternalMessageInfo

func (m *CatalogPage) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *CatalogPage) GetTotalItems() int64 {
	if m != nil {
		return m.TotalItems
	}
	return 0
}

func (m *CatalogPage) GetTotalPages() int64 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

func (m *CatalogPage) GetCurrentPage() int64 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *CatalogPage) GetSetPageTo() int64 {
	if m != nil {
		return m.SetPageTo
	}
	return 0
}

func (m *CatalogPage) GetSorting() string {
	if m != nil {
		return m.Sorting
	}
	return ""
}

func (m *CatalogPage) GetFiltering() string {
	if m != nil {
		return m.Filtering
	}
	return ""
}

func (m *CatalogPage) GetItemsPerPage() int64 {
	if m != nil {
		return m.ItemsPerPage
	}
	return 0
}

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price                int64    `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Longtext             string   `protobuf:"bytes,5,opt,name=longtext,proto3" json:"longtext,omitempty"`
	Category             string   `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	SmallImageURL        string   `protobuf:"bytes,7,opt,name=smallImageURL,proto3" json:"smallImageURL,omitempty"`
	LargeImageURL        string   `protobuf:"bytes,8,opt,name=largeImageURL,proto3" json:"largeImageURL,omitempty"`
	Disabled             bool     `protobuf:"varint,9,opt,name=disabled,proto3" json:"disabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_catalog_356a75a4028f7efd, []int{2}
}
func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (dst *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(dst, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetLongtext() string {
	if m != nil {
		return m.Longtext
	}
	return ""
}

func (m *Product) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Product) GetSmallImageURL() string {
	if m != nil {
		return m.SmallImageURL
	}
	return ""
}

func (m *Product) GetLargeImageURL() string {
	if m != nil {
		return m.LargeImageURL
	}
	return ""
}

func (m *Product) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func init() {
	proto.RegisterType((*CatalogMessages)(nil), "catalog.CatalogMessages")
	proto.RegisterType((*CatalogPage)(nil), "catalog.CatalogPage")
	proto.RegisterType((*Product)(nil), "catalog.Product")
}

func init() { proto.RegisterFile("catalog.proto", fileDescriptor_catalog_356a75a4028f7efd) }

var fileDescriptor_catalog_356a75a4028f7efd = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xd1, 0x6a, 0xdb, 0x30,
	0x18, 0x85, 0x67, 0x67, 0x89, 0xed, 0x3f, 0x4b, 0x16, 0xc4, 0x2e, 0xc4, 0x18, 0xc3, 0x98, 0x5d,
	0xf8, 0x22, 0xe4, 0x62, 0x7b, 0x83, 0xf5, 0xa6, 0x81, 0x16, 0x52, 0xd1, 0x3e, 0x80, 0x62, 0xff,
	0x15, 0x02, 0xc5, 0x32, 0x92, 0x02, 0xed, 0x13, 0xf4, 0x11, 0xfa, 0xba, 0x45, 0xb2, 0xe3, 0xd8,
	0xd0, 0x3b, 0x9d, 0xef, 0x1c, 0x1d, 0xe5, 0x04, 0xc3, 0xaa, 0xe2, 0x8e, 0x2b, 0x2d, 0x76, 0xad,
	0xd1, 0x4e, 0x93, 0xa4, 0x97, 0xc5, 0x03, 0x7c, 0xbf, 0xe9, 0x8e, 0xf7, 0x68, 0x2d, 0x17, 0x68,
	0xc9, 0x16, 0x92, 0xd6, 0xe8, 0xfa, 0x5c, 0x39, 0x1a, 0xe5, 0x51, 0xb9, 0xfc, 0xbb, 0xd9, 0x5d,
	0x2e, 0x1f, 0x3a, 0x7e, 0xfb, 0x85, 0x5d, 0x22, 0xff, 0x37, 0xb0, 0xae, 0x26, 0x05, 0xc5, 0x7b,
	0x0c, 0xcb, 0xbe, 0xf3, 0xc0, 0x05, 0x92, 0x2d, 0xa4, 0x7d, 0xd8, 0xd2, 0x28, 0x9f, 0x7d, 0x56,
	0xc8, 0x86, 0x04, 0xf9, 0x0d, 0xe0, 0xb4, 0xe3, 0x6a, 0xef, 0xf0, 0x64, 0x69, 0x9c, 0x47, 0xe5,
	0x8c, 0x8d, 0xc8, 0xe0, 0xfb, 0x6a, 0x4b, 0x67, 0x23, 0x3f, 0x10, 0x92, 0xc3, 0xb2, 0x3a, 0x1b,
	0x83, 0x8d, 0xf3, 0x9a, 0x7e, 0x0d, 0x81, 0x31, 0x22, 0xbf, 0x20, 0xb3, 0x18, 0x8e, 0x8f, 0x9a,
	0xce, 0x83, 0x7f, 0x05, 0x84, 0x42, 0x62, 0xb5, 0x71, 0xb2, 0x11, 0x74, 0x91, 0x47, 0x65, 0xc6,
	0x2e, 0xd2, 0xdf, 0x7b, 0x96, 0xca, 0xa1, 0xf1, 0x5e, 0x12, 0xbc, 0x2b, 0x20, 0x05, 0x7c, 0x93,
	0xfe, 0x07, 0x1e, 0xd0, 0x84, 0x87, 0xd3, 0x50, 0x3c, 0x61, 0xc5, 0x5b, 0x0c, 0x49, 0xbf, 0x98,
	0xac, 0x21, 0x96, 0x75, 0xf8, 0x83, 0x33, 0x16, 0xcb, 0x9a, 0xfc, 0x80, 0x79, 0x6b, 0x64, 0x85,
	0xfd, 0xe4, 0x4e, 0x78, 0xea, 0xa4, 0x53, 0x18, 0x86, 0x66, 0xac, 0x13, 0x7e, 0x63, 0x8d, 0xb6,
	0x32, 0xb2, 0x75, 0x52, 0x37, 0x61, 0x63, 0xc6, 0xc6, 0x88, 0xfc, 0x84, 0x54, 0xe9, 0x46, 0x38,
	0x7c, 0x71, 0x61, 0x62, 0xc6, 0x06, 0xed, 0xbd, 0x8a, 0x3b, 0x14, 0xda, 0xbc, 0xf6, 0x13, 0x07,
	0x4d, 0xfe, 0xc0, 0xca, 0x9e, 0xb8, 0x52, 0xfb, 0x13, 0x17, 0xf8, 0xc4, 0xee, 0xfa, 0x9d, 0x53,
	0xe8, 0x53, 0x8a, 0x1b, 0x81, 0x43, 0x2a, 0xed, 0x52, 0x13, 0xe8, 0xdf, 0xa9, 0xa5, 0xe5, 0x47,
	0x85, 0x35, 0xcd, 0xf2, 0xa8, 0x4c, 0xd9, 0xa0, 0x8f, 0x8b, 0xf0, 0x19, 0xfe, 0xfb, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x5b, 0x91, 0x27, 0x0a, 0x97, 0x02, 0x00, 0x00,
}
