// Code generated by protoc-gen-go. DO NOT EDIT.
// source: topic.proto

package catalog

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CatalogMessages struct {
	// Types that are valid to be assigned to CatalogMessage:
	//	*CatalogMessages_Product
	CatalogMessage       isCatalogMessages_CatalogMessage `protobuf_oneof:"catalogMessage"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *CatalogMessages) Reset()         { *m = CatalogMessages{} }
func (m *CatalogMessages) String() string { return proto.CompactTextString(m) }
func (*CatalogMessages) ProtoMessage()    {}
func (*CatalogMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_topic_ee776196db28579a, []int{0}
}
func (m *CatalogMessages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CatalogMessages.Unmarshal(m, b)
}
func (m *CatalogMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CatalogMessages.Marshal(b, m, deterministic)
}
func (dst *CatalogMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CatalogMessages.Merge(dst, src)
}
func (m *CatalogMessages) XXX_Size() int {
	return xxx_messageInfo_CatalogMessages.Size(m)
}
func (m *CatalogMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_CatalogMessages.DiscardUnknown(m)
}

var xxx_messageInfo_CatalogMessages proto.InternalMessageInfo

type isCatalogMessages_CatalogMessage interface {
	isCatalogMessages_CatalogMessage()
}

type CatalogMessages_Product struct {
	Product *Product `protobuf:"bytes,1,opt,name=product,proto3,oneof"`
}

func (*CatalogMessages_Product) isCatalogMessages_CatalogMessage() {}

func (m *CatalogMessages) GetCatalogMessage() isCatalogMessages_CatalogMessage {
	if m != nil {
		return m.CatalogMessage
	}
	return nil
}

func (m *CatalogMessages) GetProduct() *Product {
	if x, ok := m.GetCatalogMessage().(*CatalogMessages_Product); ok {
		return x.Product
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CatalogMessages) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _CatalogMessages_OneofMarshaler, _CatalogMessages_OneofUnmarshaler, _CatalogMessages_OneofSizer, []interface{}{
		(*CatalogMessages_Product)(nil),
	}
}

func _CatalogMessages_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*CatalogMessages)
	// catalogMessage
	switch x := m.CatalogMessage.(type) {
	case *CatalogMessages_Product:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Product); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("CatalogMessages.CatalogMessage has unexpected type %T", x)
	}
	return nil
}

func _CatalogMessages_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*CatalogMessages)
	switch tag {
	case 1: // catalogMessage.product
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Product)
		err := b.DecodeMessage(msg)
		m.CatalogMessage = &CatalogMessages_Product{msg}
		return true, err
	default:
		return false, nil
	}
}

func _CatalogMessages_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*CatalogMessages)
	// catalogMessage
	switch x := m.CatalogMessage.(type) {
	case *CatalogMessages_Product:
		s := proto.Size(x.Product)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price                int64    `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Longtext             string   `protobuf:"bytes,5,opt,name=longtext,proto3" json:"longtext,omitempty"`
	Category             string   `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	SmallImageURL        string   `protobuf:"bytes,7,opt,name=smallImageURL,proto3" json:"smallImageURL,omitempty"`
	LargeImageURL        string   `protobuf:"bytes,8,opt,name=largeImageURL,proto3" json:"largeImageURL,omitempty"`
	Disabled             bool     `protobuf:"varint,9,opt,name=disabled,proto3" json:"disabled,omitempty"`
	PimOffset            int64    `protobuf:"varint,10,opt,name=pimOffset,proto3" json:"pimOffset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_topic_ee776196db28579a, []int{1}
}
func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (dst *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(dst, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetLongtext() string {
	if m != nil {
		return m.Longtext
	}
	return ""
}

func (m *Product) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Product) GetSmallImageURL() string {
	if m != nil {
		return m.SmallImageURL
	}
	return ""
}

func (m *Product) GetLargeImageURL() string {
	if m != nil {
		return m.LargeImageURL
	}
	return ""
}

func (m *Product) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *Product) GetPimOffset() int64 {
	if m != nil {
		return m.PimOffset
	}
	return 0
}

func init() {
	proto.RegisterType((*CatalogMessages)(nil), "catalog.CatalogMessages")
	proto.RegisterType((*Product)(nil), "catalog.Product")
}

func init() { proto.RegisterFile("topic.proto", fileDescriptor_topic_ee776196db28579a) }

var fileDescriptor_topic_ee776196db28579a = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xcd, 0x4a, 0xf4, 0x30,
	0x14, 0x86, 0xbf, 0x76, 0x7e, 0xda, 0x9e, 0xf2, 0x8d, 0x43, 0x70, 0x11, 0xc4, 0x45, 0x19, 0x5c,
	0x74, 0x21, 0x5d, 0xe8, 0x1d, 0xe8, 0x46, 0x41, 0x51, 0x0b, 0x5e, 0x40, 0x26, 0x39, 0x13, 0x02,
	0x69, 0x13, 0x92, 0x08, 0x7a, 0x3d, 0xde, 0xa8, 0x34, 0x9d, 0xa9, 0x76, 0x77, 0xde, 0xe7, 0x7d,
	0x38, 0x21, 0x1c, 0x28, 0x83, 0xb1, 0x8a, 0x37, 0xd6, 0x99, 0x60, 0x48, 0xc6, 0x59, 0x60, 0xda,
	0xc8, 0xdd, 0x1b, 0x9c, 0xdd, 0x8f, 0xe3, 0x33, 0x7a, 0xcf, 0x24, 0x7a, 0x72, 0x0d, 0x99, 0x75,
	0x46, 0x7c, 0xf0, 0x40, 0x93, 0x2a, 0xa9, 0xcb, 0x9b, 0x6d, 0x73, 0xb4, 0x9b, 0xd7, 0x91, 0x3f,
	0xfc, 0x6b, 0x4f, 0xca, 0xdd, 0x16, 0x36, 0x7c, 0xb6, 0x60, 0xf7, 0x9d, 0x42, 0x76, 0x14, 0xc9,
	0x06, 0x52, 0x25, 0xe2, 0x9a, 0xa2, 0x4d, 0x95, 0x20, 0xe7, 0xb0, 0xb2, 0x4e, 0x71, 0xa4, 0x69,
	0x95, 0xd4, 0x8b, 0x76, 0x0c, 0x84, 0xc0, 0xb2, 0x67, 0x1d, 0xd2, 0x45, 0xf4, 0xe2, 0x4c, 0x2a,
	0x28, 0x05, 0x7a, 0xee, 0x94, 0x0d, 0xca, 0xf4, 0x74, 0x19, 0xab, 0xbf, 0x88, 0x5c, 0x40, 0xae,
	0x4d, 0x2f, 0x03, 0x7e, 0x06, 0xba, 0x8a, 0xf5, 0x94, 0x87, 0x8e, 0xb3, 0x80, 0xd2, 0xb8, 0x2f,
	0xba, 0x1e, 0xbb, 0x53, 0x26, 0x57, 0xf0, 0xdf, 0x77, 0x4c, 0xeb, 0xc7, 0x8e, 0x49, 0x7c, 0x6f,
	0x9f, 0x68, 0x16, 0x85, 0x39, 0x1c, 0x2c, 0xcd, 0x9c, 0xc4, 0xc9, 0xca, 0x47, 0x6b, 0x06, 0x87,
	0x77, 0x84, 0xf2, 0x6c, 0xaf, 0x51, 0xd0, 0xa2, 0x4a, 0xea, 0xbc, 0x9d, 0x32, 0xb9, 0x84, 0xc2,
	0xaa, 0xee, 0xe5, 0x70, 0xf0, 0x18, 0x28, 0xc4, 0xff, 0xfe, 0x82, 0xfd, 0x3a, 0x1e, 0xe2, 0xf6,
	0x27, 0x00, 0x00, 0xff, 0xff, 0x5e, 0xe5, 0xe5, 0x78, 0x97, 0x01, 0x00, 0x00,
}
