{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}


module Checkout exposing
    ( CheckoutMessage(..), CheckoutMessages, Product, Cart, Position, ChangeProductQuantity, OrderCart, OrderCartResonse, Stock
    , checkoutMessagesDecoder, productDecoder, cartDecoder, positionDecoder, changeProductQuantityDecoder, orderCartDecoder, orderCartResonseDecoder, stockDecoder
    , toCheckoutMessagesEncoder, toProductEncoder, toCartEncoder, toPositionEncoder, toChangeProductQuantityEncoder, toOrderCartEncoder, toOrderCartResonseEncoder, toStockEncoder
    )

{-| ProtoBuf module: `Checkout`

This module was generated automatically using

  - [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 1.0.0-beta-2
  - `protoc` 3.6.1
  - the following specification file: `checkout.proto`

To run it use [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.1.0) version 1.1.0 or higher.


# Model

@docs CheckoutMessage, CheckoutMessages, Product, Cart, Position, ChangeProductQuantity, OrderCart, OrderCartResonse, Stock


# Decoder

@docs checkoutMessagesDecoder, productDecoder, cartDecoder, positionDecoder, changeProductQuantityDecoder, orderCartDecoder, orderCartResonseDecoder, stockDecoder


# Encoder

@docs toCheckoutMessagesEncoder, toProductEncoder, toCartEncoder, toPositionEncoder, toChangeProductQuantityEncoder, toOrderCartEncoder, toOrderCartResonseEncoder, toStockEncoder

-}

import Protobuf.Decode as Decode
import Protobuf.Encode as Encode



-- MODEL


{-| CheckoutMessage
-}
type CheckoutMessage
    = CheckoutMessageChangeProductQuantity ChangeProductQuantity
    | CheckoutMessageStock Stock
    | CheckoutMessageProduct Product
    | CheckoutMessageOrderCart OrderCart


{-| `CheckoutMessages` message
-}
type alias CheckoutMessages =
    { checkoutMessage : Maybe CheckoutMessage
    }


{-| `Product` message
-}
type alias Product =
    { productID : String
    , price : Int
    , name : String
    , smallImageURL : String
    }


{-| `Cart` message
-}
type alias Cart =
    { id : String
    , positions : List Position
    }


{-| `Position` message
-}
type alias Position =
    { productID : String
    , price : Int
    , name : String
    , smallImageURL : String
    , quantity : Int
    , inStock : Bool
    , moreInStock : Bool
    }


{-| `ChangeProductQuantity` message
-}
type alias ChangeProductQuantity =
    { cartID : String
    , productID : String
    , quantity : Int
    }


{-| `OrderCart` message
-}
type alias OrderCart =
    { cartID : String
    }


{-| `OrderCartResonse` message
-}
type alias OrderCartResonse =
    { successful : Bool
    }


{-| `Stock` message
-}
type alias Stock =
    { productID : String
    , quantity : Int
    }



-- DECODER


{-| `CheckoutMessages` decoder
-}
checkoutMessagesDecoder : Decode.Decoder CheckoutMessages
checkoutMessagesDecoder =
    Decode.message (CheckoutMessages Nothing)
        [ Decode.oneOf
            [ ( 1, Decode.map CheckoutMessageChangeProductQuantity changeProductQuantityDecoder )
            , ( 2, Decode.map CheckoutMessageStock stockDecoder )
            , ( 3, Decode.map CheckoutMessageProduct productDecoder )
            , ( 4, Decode.map CheckoutMessageOrderCart orderCartDecoder )
            ]
            setCheckoutMessage
        ]


{-| `Product` decoder
-}
productDecoder : Decode.Decoder Product
productDecoder =
    Decode.message (Product "" 0 "" "")
        [ Decode.optional 1 Decode.string setProductID
        , Decode.optional 2 Decode.int32 setPrice
        , Decode.optional 3 Decode.string setName
        , Decode.optional 4 Decode.string setSmallImageURL
        ]


{-| `Cart` decoder
-}
cartDecoder : Decode.Decoder Cart
cartDecoder =
    Decode.message (Cart "" [])
        [ Decode.optional 1 Decode.string setId
        , Decode.repeated 2 positionDecoder .positions setPositions
        ]


{-| `Position` decoder
-}
positionDecoder : Decode.Decoder Position
positionDecoder =
    Decode.message (Position "" 0 "" "" 0 False False)
        [ Decode.optional 1 Decode.string setProductID
        , Decode.optional 2 Decode.int32 setPrice
        , Decode.optional 3 Decode.string setName
        , Decode.optional 4 Decode.string setSmallImageURL
        , Decode.optional 6 Decode.int32 setQuantity
        , Decode.optional 7 Decode.bool setInStock
        , Decode.optional 8 Decode.bool setMoreInStock
        ]


{-| `ChangeProductQuantity` decoder
-}
changeProductQuantityDecoder : Decode.Decoder ChangeProductQuantity
changeProductQuantityDecoder =
    Decode.message (ChangeProductQuantity "" "" 0)
        [ Decode.optional 3 Decode.string setCartID
        , Decode.optional 1 Decode.string setProductID
        , Decode.optional 2 Decode.int32 setQuantity
        ]


{-| `OrderCart` decoder
-}
orderCartDecoder : Decode.Decoder OrderCart
orderCartDecoder =
    Decode.message (OrderCart "")
        [ Decode.optional 1 Decode.string setCartID
        ]


{-| `OrderCartResonse` decoder
-}
orderCartResonseDecoder : Decode.Decoder OrderCartResonse
orderCartResonseDecoder =
    Decode.message (OrderCartResonse False)
        [ Decode.optional 1 Decode.bool setSuccessful
        ]


{-| `Stock` decoder
-}
stockDecoder : Decode.Decoder Stock
stockDecoder =
    Decode.message (Stock "" 0)
        [ Decode.optional 1 Decode.string setProductID
        , Decode.optional 2 Decode.int32 setQuantity
        ]



-- ENCODER


toCheckoutMessageEncoder : CheckoutMessage -> ( Int, Encode.Encoder )
toCheckoutMessageEncoder model =
    case model of
        CheckoutMessageChangeProductQuantity value ->
            ( 1, toChangeProductQuantityEncoder value )

        CheckoutMessageStock value ->
            ( 2, toStockEncoder value )

        CheckoutMessageProduct value ->
            ( 3, toProductEncoder value )

        CheckoutMessageOrderCart value ->
            ( 4, toOrderCartEncoder value )


{-| `CheckoutMessages` encoder
-}
toCheckoutMessagesEncoder : CheckoutMessages -> Encode.Encoder
toCheckoutMessagesEncoder model =
    Encode.message
        [ Maybe.withDefault ( 0, Encode.none ) <| Maybe.map toCheckoutMessageEncoder model.checkoutMessage
        ]


{-| `Product` encoder
-}
toProductEncoder : Product -> Encode.Encoder
toProductEncoder model =
    Encode.message
        [ ( 1, Encode.string model.productID )
        , ( 2, Encode.int32 model.price )
        , ( 3, Encode.string model.name )
        , ( 4, Encode.string model.smallImageURL )
        ]


{-| `Cart` encoder
-}
toCartEncoder : Cart -> Encode.Encoder
toCartEncoder model =
    Encode.message
        [ ( 1, Encode.string model.id )
        , ( 2, Encode.list toPositionEncoder model.positions )
        ]


{-| `Position` encoder
-}
toPositionEncoder : Position -> Encode.Encoder
toPositionEncoder model =
    Encode.message
        [ ( 1, Encode.string model.productID )
        , ( 2, Encode.int32 model.price )
        , ( 3, Encode.string model.name )
        , ( 4, Encode.string model.smallImageURL )
        , ( 6, Encode.int32 model.quantity )
        , ( 7, Encode.bool model.inStock )
        , ( 8, Encode.bool model.moreInStock )
        ]


{-| `ChangeProductQuantity` encoder
-}
toChangeProductQuantityEncoder : ChangeProductQuantity -> Encode.Encoder
toChangeProductQuantityEncoder model =
    Encode.message
        [ ( 3, Encode.string model.cartID )
        , ( 1, Encode.string model.productID )
        , ( 2, Encode.int32 model.quantity )
        ]


{-| `OrderCart` encoder
-}
toOrderCartEncoder : OrderCart -> Encode.Encoder
toOrderCartEncoder model =
    Encode.message
        [ ( 1, Encode.string model.cartID )
        ]


{-| `OrderCartResonse` encoder
-}
toOrderCartResonseEncoder : OrderCartResonse -> Encode.Encoder
toOrderCartResonseEncoder model =
    Encode.message
        [ ( 1, Encode.bool model.successful )
        ]


{-| `Stock` encoder
-}
toStockEncoder : Stock -> Encode.Encoder
toStockEncoder model =
    Encode.message
        [ ( 1, Encode.string model.productID )
        , ( 2, Encode.int32 model.quantity )
        ]



-- SETTERS


setCheckoutMessage : a -> { b | checkoutMessage : a } -> { b | checkoutMessage : a }
setCheckoutMessage value model =
    { model | checkoutMessage = value }


setProductID : a -> { b | productID : a } -> { b | productID : a }
setProductID value model =
    { model | productID = value }


setPrice : a -> { b | price : a } -> { b | price : a }
setPrice value model =
    { model | price = value }


setName : a -> { b | name : a } -> { b | name : a }
setName value model =
    { model | name = value }


setSmallImageURL : a -> { b | smallImageURL : a } -> { b | smallImageURL : a }
setSmallImageURL value model =
    { model | smallImageURL = value }


setId : a -> { b | id : a } -> { b | id : a }
setId value model =
    { model | id = value }


setPositions : a -> { b | positions : a } -> { b | positions : a }
setPositions value model =
    { model | positions = value }


setQuantity : a -> { b | quantity : a } -> { b | quantity : a }
setQuantity value model =
    { model | quantity = value }


setInStock : a -> { b | inStock : a } -> { b | inStock : a }
setInStock value model =
    { model | inStock = value }


setMoreInStock : a -> { b | moreInStock : a } -> { b | moreInStock : a }
setMoreInStock value model =
    { model | moreInStock = value }


setCartID : a -> { b | cartID : a } -> { b | cartID : a }
setCartID value model =
    { model | cartID = value }


setSuccessful : a -> { b | successful : a } -> { b | successful : a }
setSuccessful value model =
    { model | successful = value }
