// Code generated by protoc-gen-go. DO NOT EDIT.
// source: topic.proto

package fulfilment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TopicMessage struct {
	// Types that are valid to be assigned to Messages:
	//	*TopicMessage_StockCorrected
	Messages             isTopicMessage_Messages `protobuf_oneof:"messages"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *TopicMessage) Reset()         { *m = TopicMessage{} }
func (m *TopicMessage) String() string { return proto.CompactTextString(m) }
func (*TopicMessage) ProtoMessage()    {}
func (*TopicMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7312ad0e4fa171e8, []int{0}
}

func (m *TopicMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicMessage.Unmarshal(m, b)
}
func (m *TopicMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicMessage.Marshal(b, m, deterministic)
}
func (m *TopicMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicMessage.Merge(m, src)
}
func (m *TopicMessage) XXX_Size() int {
	return xxx_messageInfo_TopicMessage.Size(m)
}
func (m *TopicMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TopicMessage proto.InternalMessageInfo

type isTopicMessage_Messages interface {
	isTopicMessage_Messages()
}

type TopicMessage_StockCorrected struct {
	StockCorrected *StockCorrected `protobuf:"bytes,1,opt,name=stockCorrected,proto3,oneof"`
}

func (*TopicMessage_StockCorrected) isTopicMessage_Messages() {}

func (m *TopicMessage) GetMessages() isTopicMessage_Messages {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *TopicMessage) GetStockCorrected() *StockCorrected {
	if x, ok := m.GetMessages().(*TopicMessage_StockCorrected); ok {
		return x.StockCorrected
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TopicMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TopicMessage_StockCorrected)(nil),
	}
}

type StockCorrected struct {
	ProductID            string   `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	QuantityChange       int64    `protobuf:"varint,2,opt,name=quantityChange,proto3" json:"quantityChange,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockCorrected) Reset()         { *m = StockCorrected{} }
func (m *StockCorrected) String() string { return proto.CompactTextString(m) }
func (*StockCorrected) ProtoMessage()    {}
func (*StockCorrected) Descriptor() ([]byte, []int) {
	return fileDescriptor_7312ad0e4fa171e8, []int{1}
}

func (m *StockCorrected) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockCorrected.Unmarshal(m, b)
}
func (m *StockCorrected) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockCorrected.Marshal(b, m, deterministic)
}
func (m *StockCorrected) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockCorrected.Merge(m, src)
}
func (m *StockCorrected) XXX_Size() int {
	return xxx_messageInfo_StockCorrected.Size(m)
}
func (m *StockCorrected) XXX_DiscardUnknown() {
	xxx_messageInfo_StockCorrected.DiscardUnknown(m)
}

var xxx_messageInfo_StockCorrected proto.InternalMessageInfo

func (m *StockCorrected) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *StockCorrected) GetQuantityChange() int64 {
	if m != nil {
		return m.QuantityChange
	}
	return 0
}

func init() {
	proto.RegisterType((*TopicMessage)(nil), "fulfilment.TopicMessage")
	proto.RegisterType((*StockCorrected)(nil), "fulfilment.StockCorrected")
}

func init() { proto.RegisterFile("topic.proto", fileDescriptor_7312ad0e4fa171e8) }

var fileDescriptor_7312ad0e4fa171e8 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xc9, 0x2f, 0xc8,
	0x4c, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0x2b, 0xcd, 0x49, 0xcb, 0xcc, 0xc9,
	0x4d, 0xcd, 0x2b, 0x51, 0x4a, 0xe0, 0xe2, 0x09, 0x01, 0x49, 0xf9, 0xa6, 0x16, 0x17, 0x27, 0xa6,
	0xa7, 0x0a, 0xb9, 0x70, 0xf1, 0x15, 0x97, 0xe4, 0x27, 0x67, 0x3b, 0xe7, 0x17, 0x15, 0xa5, 0x26,
	0x97, 0xa4, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0x49, 0xe9, 0x21, 0x34, 0xe9, 0x05,
	0xa3, 0xa8, 0xf0, 0x60, 0x08, 0x42, 0xd3, 0xe3, 0xc4, 0xc5, 0xc5, 0x91, 0x0b, 0x31, 0xb0, 0x58,
	0x29, 0x8c, 0x8b, 0x0f, 0x55, 0xbd, 0x90, 0x0c, 0x17, 0x67, 0x41, 0x51, 0x7e, 0x4a, 0x69, 0x72,
	0x89, 0xa7, 0x0b, 0xd8, 0x78, 0xce, 0x20, 0x84, 0x80, 0x90, 0x1a, 0x17, 0x5f, 0x61, 0x69, 0x62,
	0x5e, 0x49, 0x66, 0x49, 0xa5, 0x73, 0x46, 0x62, 0x5e, 0x7a, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06,
	0x73, 0x10, 0x9a, 0x68, 0x12, 0x1b, 0xd8, 0x33, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5f,
	0xff, 0x9a, 0x28, 0xdb, 0x00, 0x00, 0x00,
}
