// Code generated by protoc-gen-go. DO NOT EDIT.
// source: checkout.proto

package checkout

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CheckoutMessages struct {
	// Types that are valid to be assigned to CheckoutMessage:
	//	*CheckoutMessages_ChangeProductQuantity
	//	*CheckoutMessages_Stock
	//	*CheckoutMessages_Product
	//	*CheckoutMessages_CartOrder
	CheckoutMessage      isCheckoutMessages_CheckoutMessage `protobuf_oneof:"checkoutMessage"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *CheckoutMessages) Reset()         { *m = CheckoutMessages{} }
func (m *CheckoutMessages) String() string { return proto.CompactTextString(m) }
func (*CheckoutMessages) ProtoMessage()    {}
func (*CheckoutMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkout_6263f28b59a473bf, []int{0}
}
func (m *CheckoutMessages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckoutMessages.Unmarshal(m, b)
}
func (m *CheckoutMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckoutMessages.Marshal(b, m, deterministic)
}
func (dst *CheckoutMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckoutMessages.Merge(dst, src)
}
func (m *CheckoutMessages) XXX_Size() int {
	return xxx_messageInfo_CheckoutMessages.Size(m)
}
func (m *CheckoutMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckoutMessages.DiscardUnknown(m)
}

var xxx_messageInfo_CheckoutMessages proto.InternalMessageInfo

type isCheckoutMessages_CheckoutMessage interface {
	isCheckoutMessages_CheckoutMessage()
}

type CheckoutMessages_ChangeProductQuantity struct {
	ChangeProductQuantity *ChangeProductQuantity `protobuf:"bytes,1,opt,name=changeProductQuantity,proto3,oneof"`
}

type CheckoutMessages_Stock struct {
	Stock *Stock `protobuf:"bytes,2,opt,name=stock,proto3,oneof"`
}

type CheckoutMessages_Product struct {
	Product *Product `protobuf:"bytes,3,opt,name=product,proto3,oneof"`
}

type CheckoutMessages_CartOrder struct {
	CartOrder *OrderCart `protobuf:"bytes,4,opt,name=cartOrder,proto3,oneof"`
}

func (*CheckoutMessages_ChangeProductQuantity) isCheckoutMessages_CheckoutMessage() {}

func (*CheckoutMessages_Stock) isCheckoutMessages_CheckoutMessage() {}

func (*CheckoutMessages_Product) isCheckoutMessages_CheckoutMessage() {}

func (*CheckoutMessages_CartOrder) isCheckoutMessages_CheckoutMessage() {}

func (m *CheckoutMessages) GetCheckoutMessage() isCheckoutMessages_CheckoutMessage {
	if m != nil {
		return m.CheckoutMessage
	}
	return nil
}

func (m *CheckoutMessages) GetChangeProductQuantity() *ChangeProductQuantity {
	if x, ok := m.GetCheckoutMessage().(*CheckoutMessages_ChangeProductQuantity); ok {
		return x.ChangeProductQuantity
	}
	return nil
}

func (m *CheckoutMessages) GetStock() *Stock {
	if x, ok := m.GetCheckoutMessage().(*CheckoutMessages_Stock); ok {
		return x.Stock
	}
	return nil
}

func (m *CheckoutMessages) GetProduct() *Product {
	if x, ok := m.GetCheckoutMessage().(*CheckoutMessages_Product); ok {
		return x.Product
	}
	return nil
}

func (m *CheckoutMessages) GetCartOrder() *OrderCart {
	if x, ok := m.GetCheckoutMessage().(*CheckoutMessages_CartOrder); ok {
		return x.CartOrder
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CheckoutMessages) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _CheckoutMessages_OneofMarshaler, _CheckoutMessages_OneofUnmarshaler, _CheckoutMessages_OneofSizer, []interface{}{
		(*CheckoutMessages_ChangeProductQuantity)(nil),
		(*CheckoutMessages_Stock)(nil),
		(*CheckoutMessages_Product)(nil),
		(*CheckoutMessages_CartOrder)(nil),
	}
}

func _CheckoutMessages_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*CheckoutMessages)
	// checkoutMessage
	switch x := m.CheckoutMessage.(type) {
	case *CheckoutMessages_ChangeProductQuantity:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ChangeProductQuantity); err != nil {
			return err
		}
	case *CheckoutMessages_Stock:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Stock); err != nil {
			return err
		}
	case *CheckoutMessages_Product:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Product); err != nil {
			return err
		}
	case *CheckoutMessages_CartOrder:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CartOrder); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("CheckoutMessages.CheckoutMessage has unexpected type %T", x)
	}
	return nil
}

func _CheckoutMessages_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*CheckoutMessages)
	switch tag {
	case 1: // checkoutMessage.changeProductQuantity
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ChangeProductQuantity)
		err := b.DecodeMessage(msg)
		m.CheckoutMessage = &CheckoutMessages_ChangeProductQuantity{msg}
		return true, err
	case 2: // checkoutMessage.stock
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Stock)
		err := b.DecodeMessage(msg)
		m.CheckoutMessage = &CheckoutMessages_Stock{msg}
		return true, err
	case 3: // checkoutMessage.product
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Product)
		err := b.DecodeMessage(msg)
		m.CheckoutMessage = &CheckoutMessages_Product{msg}
		return true, err
	case 4: // checkoutMessage.cartOrder
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OrderCart)
		err := b.DecodeMessage(msg)
		m.CheckoutMessage = &CheckoutMessages_CartOrder{msg}
		return true, err
	default:
		return false, nil
	}
}

func _CheckoutMessages_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*CheckoutMessages)
	// checkoutMessage
	switch x := m.CheckoutMessage.(type) {
	case *CheckoutMessages_ChangeProductQuantity:
		s := proto.Size(x.ChangeProductQuantity)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CheckoutMessages_Stock:
		s := proto.Size(x.Stock)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CheckoutMessages_Product:
		s := proto.Size(x.Product)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CheckoutMessages_CartOrder:
		s := proto.Size(x.CartOrder)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Product struct {
	ProductID            string   `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	Price                int64    `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	SmallImageURL        string   `protobuf:"bytes,4,opt,name=smallImageURL,proto3" json:"smallImageURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkout_6263f28b59a473bf, []int{1}
}
func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (dst *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(dst, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *Product) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Product) GetSmallImageURL() string {
	if m != nil {
		return m.SmallImageURL
	}
	return ""
}

type Cart struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Positions            []*Position `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Cart) Reset()         { *m = Cart{} }
func (m *Cart) String() string { return proto.CompactTextString(m) }
func (*Cart) ProtoMessage()    {}
func (*Cart) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkout_6263f28b59a473bf, []int{2}
}
func (m *Cart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cart.Unmarshal(m, b)
}
func (m *Cart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cart.Marshal(b, m, deterministic)
}
func (dst *Cart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cart.Merge(dst, src)
}
func (m *Cart) XXX_Size() int {
	return xxx_messageInfo_Cart.Size(m)
}
func (m *Cart) XXX_DiscardUnknown() {
	xxx_messageInfo_Cart.DiscardUnknown(m)
}

var xxx_messageInfo_Cart proto.InternalMessageInfo

func (m *Cart) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Cart) GetPositions() []*Position {
	if m != nil {
		return m.Positions
	}
	return nil
}

type Position struct {
	ProductID            string   `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	Price                int64    `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	SmallImageURL        string   `protobuf:"bytes,4,opt,name=smallImageURL,proto3" json:"smallImageURL,omitempty"`
	Quantity             int64    `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	InStock              bool     `protobuf:"varint,7,opt,name=inStock,proto3" json:"inStock,omitempty"`
	MoreInStock          bool     `protobuf:"varint,8,opt,name=moreInStock,proto3" json:"moreInStock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkout_6263f28b59a473bf, []int{3}
}
func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (dst *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(dst, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *Position) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Position) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Position) GetSmallImageURL() string {
	if m != nil {
		return m.SmallImageURL
	}
	return ""
}

func (m *Position) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Position) GetInStock() bool {
	if m != nil {
		return m.InStock
	}
	return false
}

func (m *Position) GetMoreInStock() bool {
	if m != nil {
		return m.MoreInStock
	}
	return false
}

type ChangeProductQuantity struct {
	CartID               string   `protobuf:"bytes,3,opt,name=cartID,proto3" json:"cartID,omitempty"`
	ProductID            string   `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	Quantity             int64    `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeProductQuantity) Reset()         { *m = ChangeProductQuantity{} }
func (m *ChangeProductQuantity) String() string { return proto.CompactTextString(m) }
func (*ChangeProductQuantity) ProtoMessage()    {}
func (*ChangeProductQuantity) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkout_6263f28b59a473bf, []int{4}
}
func (m *ChangeProductQuantity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeProductQuantity.Unmarshal(m, b)
}
func (m *ChangeProductQuantity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeProductQuantity.Marshal(b, m, deterministic)
}
func (dst *ChangeProductQuantity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeProductQuantity.Merge(dst, src)
}
func (m *ChangeProductQuantity) XXX_Size() int {
	return xxx_messageInfo_ChangeProductQuantity.Size(m)
}
func (m *ChangeProductQuantity) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeProductQuantity.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeProductQuantity proto.InternalMessageInfo

func (m *ChangeProductQuantity) GetCartID() string {
	if m != nil {
		return m.CartID
	}
	return ""
}

func (m *ChangeProductQuantity) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *ChangeProductQuantity) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type OrderCart struct {
	CartID               string   `protobuf:"bytes,1,opt,name=cartID,proto3" json:"cartID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderCart) Reset()         { *m = OrderCart{} }
func (m *OrderCart) String() string { return proto.CompactTextString(m) }
func (*OrderCart) ProtoMessage()    {}
func (*OrderCart) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkout_6263f28b59a473bf, []int{5}
}
func (m *OrderCart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCart.Unmarshal(m, b)
}
func (m *OrderCart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCart.Marshal(b, m, deterministic)
}
func (dst *OrderCart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCart.Merge(dst, src)
}
func (m *OrderCart) XXX_Size() int {
	return xxx_messageInfo_OrderCart.Size(m)
}
func (m *OrderCart) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCart.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCart proto.InternalMessageInfo

func (m *OrderCart) GetCartID() string {
	if m != nil {
		return m.CartID
	}
	return ""
}

type OrderCartResonse struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderCartResonse) Reset()         { *m = OrderCartResonse{} }
func (m *OrderCartResonse) String() string { return proto.CompactTextString(m) }
func (*OrderCartResonse) ProtoMessage()    {}
func (*OrderCartResonse) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkout_6263f28b59a473bf, []int{6}
}
func (m *OrderCartResonse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCartResonse.Unmarshal(m, b)
}
func (m *OrderCartResonse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCartResonse.Marshal(b, m, deterministic)
}
func (dst *OrderCartResonse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCartResonse.Merge(dst, src)
}
func (m *OrderCartResonse) XXX_Size() int {
	return xxx_messageInfo_OrderCartResonse.Size(m)
}
func (m *OrderCartResonse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCartResonse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCartResonse proto.InternalMessageInfo

func (m *OrderCartResonse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type Stock struct {
	ProductID            string   `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	Quantity             int64    `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stock) Reset()         { *m = Stock{} }
func (m *Stock) String() string { return proto.CompactTextString(m) }
func (*Stock) ProtoMessage()    {}
func (*Stock) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkout_6263f28b59a473bf, []int{7}
}
func (m *Stock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stock.Unmarshal(m, b)
}
func (m *Stock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stock.Marshal(b, m, deterministic)
}
func (dst *Stock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stock.Merge(dst, src)
}
func (m *Stock) XXX_Size() int {
	return xxx_messageInfo_Stock.Size(m)
}
func (m *Stock) XXX_DiscardUnknown() {
	xxx_messageInfo_Stock.DiscardUnknown(m)
}

var xxx_messageInfo_Stock proto.InternalMessageInfo

func (m *Stock) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *Stock) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func init() {
	proto.RegisterType((*CheckoutMessages)(nil), "checkout.CheckoutMessages")
	proto.RegisterType((*Product)(nil), "checkout.Product")
	proto.RegisterType((*Cart)(nil), "checkout.Cart")
	proto.RegisterType((*Position)(nil), "checkout.Position")
	proto.RegisterType((*ChangeProductQuantity)(nil), "checkout.ChangeProductQuantity")
	proto.RegisterType((*OrderCart)(nil), "checkout.OrderCart")
	proto.RegisterType((*OrderCartResonse)(nil), "checkout.OrderCartResonse")
	proto.RegisterType((*Stock)(nil), "checkout.Stock")
}

func init() { proto.RegisterFile("checkout.proto", fileDescriptor_checkout_6263f28b59a473bf) }

var fileDescriptor_checkout_6263f28b59a473bf = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x14, 0x6c, 0xd2, 0x6d, 0x93, 0xbc, 0x8a, 0xfd, 0x78, 0xb0, 0x28, 0x42, 0x08, 0x22, 0x83, 0x44,
	0x2f, 0xac, 0x50, 0xf7, 0x17, 0x40, 0xf7, 0x90, 0x48, 0x20, 0xc0, 0x08, 0x71, 0x0e, 0x8e, 0xe9,
	0x5a, 0x9b, 0xc6, 0xc1, 0x76, 0x0e, 0xfb, 0x1b, 0xf8, 0x77, 0xfc, 0x22, 0x14, 0xc7, 0xf9, 0xa8,
	0x54, 0x09, 0x89, 0x03, 0xc7, 0x99, 0x37, 0x6f, 0x3a, 0x53, 0xbf, 0xc0, 0x29, 0xbb, 0xe5, 0xec,
	0x4e, 0x36, 0xe6, 0xaa, 0x56, 0xd2, 0x48, 0x0c, 0x7b, 0x4c, 0x7e, 0xf9, 0x70, 0xbe, 0x75, 0xe0,
	0x03, 0xd7, 0x3a, 0xdf, 0x71, 0x8d, 0xdf, 0xe0, 0x92, 0xdd, 0xe6, 0xd5, 0x8e, 0x7f, 0x52, 0xb2,
	0x68, 0x98, 0xf9, 0xdc, 0xe4, 0x95, 0x11, 0xe6, 0x3e, 0xf6, 0x12, 0x6f, 0xbd, 0xda, 0x3c, 0xbf,
	0x1a, 0xec, 0xb6, 0xc7, 0x64, 0xe9, 0x8c, 0x1e, 0xdf, 0xc7, 0x57, 0xb0, 0xd0, 0x46, 0xb2, 0xbb,
	0xd8, 0xb7, 0x46, 0x67, 0xa3, 0xd1, 0x97, 0x96, 0x4e, 0x67, 0xb4, 0x9b, 0xe3, 0x6b, 0x08, 0xea,
	0x6e, 0x37, 0x9e, 0x5b, 0xe9, 0xc5, 0x28, 0x75, 0xa6, 0xe9, 0x8c, 0xf6, 0x1a, 0xbc, 0x86, 0x88,
	0xe5, 0xca, 0x7c, 0x54, 0x05, 0x57, 0xf1, 0x89, 0x5d, 0x78, 0x38, 0x2e, 0x58, 0x7a, 0x9b, 0xab,
	0x76, 0x65, 0xd4, 0xbd, 0xbb, 0x80, 0x33, 0x76, 0xd8, 0x9c, 0xdc, 0x43, 0xe0, 0xdc, 0xf1, 0x29,
	0x44, 0xce, 0x3d, 0xbb, 0xb1, 0xbd, 0x23, 0x3a, 0x12, 0xf8, 0x08, 0x16, 0xb5, 0x12, 0x8c, 0xdb,
	0x22, 0x73, 0xda, 0x81, 0x96, 0x35, 0xc2, 0x94, 0xdc, 0x66, 0x8e, 0x68, 0x07, 0xf0, 0x25, 0x3c,
	0xd0, 0xfb, 0xbc, 0x2c, 0xb3, 0x7d, 0xbe, 0xe3, 0x5f, 0xe9, 0x7b, 0x1b, 0x30, 0xa2, 0x87, 0x24,
	0x49, 0xe1, 0xa4, 0x8d, 0x88, 0xa7, 0xe0, 0x8b, 0xc2, 0xfd, 0xa0, 0x2f, 0x0a, 0x7c, 0x03, 0x51,
	0x2d, 0xb5, 0x30, 0x42, 0x56, 0x3a, 0xf6, 0x93, 0xf9, 0x7a, 0xb5, 0xc1, 0xc9, 0x7f, 0xe1, 0x46,
	0x74, 0x14, 0x91, 0xdf, 0x1e, 0x84, 0x3d, 0xff, 0xbf, 0x6b, 0xe0, 0x13, 0x08, 0x7f, 0xf6, 0xd7,
	0xb2, 0xb4, 0xa6, 0x03, 0xc6, 0x18, 0x02, 0x51, 0xd9, 0x87, 0x8e, 0x83, 0xc4, 0x5b, 0x87, 0xb4,
	0x87, 0x98, 0xc0, 0x6a, 0x2f, 0x15, 0xcf, 0xdc, 0x34, 0xb4, 0xd3, 0x29, 0x45, 0x04, 0x5c, 0x1e,
	0xbd, 0x35, 0x7c, 0x0c, 0xcb, 0xf6, 0x49, 0xb3, 0x1b, 0x97, 0xd6, 0xa1, 0xbf, 0x14, 0x9f, 0xc6,
	0xf4, 0x0f, 0x63, 0x92, 0x17, 0x10, 0x0d, 0x17, 0x33, 0xb1, 0xf7, 0xa6, 0xf6, 0x64, 0x03, 0xe7,
	0x83, 0x88, 0x72, 0x2d, 0x2b, 0xcd, 0xf1, 0x19, 0x80, 0x6e, 0x18, 0xe3, 0x5a, 0xff, 0x68, 0x4a,
	0xab, 0x0f, 0xe9, 0x84, 0x21, 0x6f, 0x61, 0xd1, 0xd5, 0xfd, 0xe7, 0x6c, 0xdf, 0x97, 0xf6, 0xfb,
	0xbd, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x28, 0x33, 0xea, 0xd1, 0x03, 0x00, 0x00,
}
